package com.venues.bms.po;

public class AdAdvert {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ad.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ad.ADName
     *
     * @mbggenerated
     */
    private String adname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_ad.ADImage
     *
     * @mbggenerated
     */
    private String adimage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ad.ID
     *
     * @return the value of tbl_ad.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ad.ID
     *
     * @param id the value for tbl_ad.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ad.ADName
     *
     * @return the value of tbl_ad.ADName
     *
     * @mbggenerated
     */
    public String getAdname() {
        return adname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ad.ADName
     *
     * @param adname the value for tbl_ad.ADName
     *
     * @mbggenerated
     */
    public void setAdname(String adname) {
        this.adname = adname == null ? null : adname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_ad.ADImage
     *
     * @return the value of tbl_ad.ADImage
     *
     * @mbggenerated
     */
    public String getAdimage() {
        return adimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_ad.ADImage
     *
     * @param adimage the value for tbl_ad.ADImage
     *
     * @mbggenerated
     */
    public void setAdimage(String adimage) {
        this.adimage = adimage == null ? null : adimage.trim();
    }
}