package com.venues.bms.po;

public class AtAttr {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_attr.Id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_attr.AttrGroupId
	 *
	 * @mbggenerated
	 */
	private Integer attrGroupId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_attr.AttrName
	 *
	 * @mbggenerated
	 */
	private String attrName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_attr.AttrEnName
	 *
	 * @mbggenerated
	 */
	private String attrEnName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_attr.AttrCode
	 *
	 * @mbggenerated
	 */
	private String attrCode;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_attr.AttrType
	 *
	 * @mbggenerated
	 */
	private String attrType;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_attr.DataSource
	 *
	 * @mbggenerated
	 */
	private String dataSource;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_attr.Memo
	 *
	 * @mbggenerated
	 */
	private String memo;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_attr.Sort
	 *
	 * @mbggenerated
	 */
	private String sort;

	private String required;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_attr.Id
	 *
	 * @return the value of tbl_attr.Id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_attr.Id
	 *
	 * @param id the value for tbl_attr.Id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_attr.AttrGroupId
	 *
	 * @return the value of tbl_attr.AttrGroupId
	 *
	 * @mbggenerated
	 */
	public Integer getAttrGroupId() {
		return attrGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_attr.AttrGroupId
	 *
	 * @param attrGroupId the value for tbl_attr.AttrGroupId
	 *
	 * @mbggenerated
	 */
	public void setAttrGroupId(Integer attrGroupId) {
		this.attrGroupId = attrGroupId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_attr.AttrName
	 *
	 * @return the value of tbl_attr.AttrName
	 *
	 * @mbggenerated
	 */
	public String getAttrName() {
		return attrName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_attr.AttrName
	 *
	 * @param attrName the value for tbl_attr.AttrName
	 *
	 * @mbggenerated
	 */
	public void setAttrName(String attrName) {
		this.attrName = attrName == null ? null : attrName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_attr.AttrEnName
	 *
	 * @return the value of tbl_attr.AttrEnName
	 *
	 * @mbggenerated
	 */
	public String getAttrEnName() {
		return attrEnName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_attr.AttrEnName
	 *
	 * @param attrEnName the value for tbl_attr.AttrEnName
	 *
	 * @mbggenerated
	 */
	public void setAttrEnName(String attrEnName) {
		this.attrEnName = attrEnName == null ? null : attrEnName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_attr.AttrCode
	 *
	 * @return the value of tbl_attr.AttrCode
	 *
	 * @mbggenerated
	 */
	public String getAttrCode() {
		return attrCode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_attr.AttrCode
	 *
	 * @param attrCode the value for tbl_attr.AttrCode
	 *
	 * @mbggenerated
	 */
	public void setAttrCode(String attrCode) {
		this.attrCode = attrCode == null ? null : attrCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_attr.AttrType
	 *
	 * @return the value of tbl_attr.AttrType
	 *
	 * @mbggenerated
	 */
	public String getAttrType() {
		return attrType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_attr.AttrType
	 *
	 * @param attrType the value for tbl_attr.AttrType
	 *
	 * @mbggenerated
	 */
	public void setAttrType(String attrType) {
		this.attrType = attrType == null ? null : attrType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_attr.DataSource
	 *
	 * @return the value of tbl_attr.DataSource
	 *
	 * @mbggenerated
	 */
	public String getDataSource() {
		return dataSource;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_attr.DataSource
	 *
	 * @param dataSource the value for tbl_attr.DataSource
	 *
	 * @mbggenerated
	 */
	public void setDataSource(String dataSource) {
		this.dataSource = dataSource == null ? null : dataSource.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_attr.Memo
	 *
	 * @return the value of tbl_attr.Memo
	 *
	 * @mbggenerated
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_attr.Memo
	 *
	 * @param memo the value for tbl_attr.Memo
	 *
	 * @mbggenerated
	 */
	public void setMemo(String memo) {
		this.memo = memo == null ? null : memo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_attr.Sort
	 *
	 * @return the value of tbl_attr.Sort
	 *
	 * @mbggenerated
	 */
	public String getSort() {
		return sort;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_attr.Sort
	 *
	 * @param sort the value for tbl_attr.Sort
	 *
	 * @mbggenerated
	 */
	public void setSort(String sort) {
		this.sort = sort == null ? null : sort.trim();
	}

	public String getRequired() {
		return required;
	}

	public void setRequired(String required) {
		this.required = required;
	}

}