package com.venues.bms.po;

public class AtAttrGroup {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_attr_group.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_attr_group.VenueType
     *
     * @mbggenerated
     */
    private String venueType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_attr_group.AttrGroupName
     *
     * @mbggenerated
     */
    private String attrGroupName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_attr_group.Sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_attr_group.Id
     *
     * @return the value of tbl_attr_group.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_attr_group.Id
     *
     * @param id the value for tbl_attr_group.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_attr_group.VenueType
     *
     * @return the value of tbl_attr_group.VenueType
     *
     * @mbggenerated
     */
    public String getVenueType() {
        return venueType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_attr_group.VenueType
     *
     * @param venueType the value for tbl_attr_group.VenueType
     *
     * @mbggenerated
     */
    public void setVenueType(String venueType) {
        this.venueType = venueType == null ? null : venueType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_attr_group.AttrGroupName
     *
     * @return the value of tbl_attr_group.AttrGroupName
     *
     * @mbggenerated
     */
    public String getAttrGroupName() {
        return attrGroupName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_attr_group.AttrGroupName
     *
     * @param attrGroupName the value for tbl_attr_group.AttrGroupName
     *
     * @mbggenerated
     */
    public void setAttrGroupName(String attrGroupName) {
        this.attrGroupName = attrGroupName == null ? null : attrGroupName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_attr_group.Sort
     *
     * @return the value of tbl_attr_group.Sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_attr_group.Sort
     *
     * @param sort the value for tbl_attr_group.Sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}