package com.venues.bms.po;

import java.util.Date;

public class BkBook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.BookVenueID
     *
     * @mbggenerated
     */
    private Integer bookVenueID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.BookVenueSequence
     *
     * @mbggenerated
     */
    private String bookVenueSequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.BookCreateTIme
     *
     * @mbggenerated
     */
    private Date bookCreateTIme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.BookBackgroundImg
     *
     * @mbggenerated
     */
    private String bookBackgroundImg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.BookFacebookLink
     *
     * @mbggenerated
     */
    private String bookFacebookLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.BookTwitterLink
     *
     * @mbggenerated
     */
    private String bookTwitterLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.BookWeixinLink
     *
     * @mbggenerated
     */
    private String bookWeixinLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.BookWeiboLink
     *
     * @mbggenerated
     */
    private String bookWeiboLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_book.AllCurBookInfo
     *
     * @mbggenerated
     */
    private String allCurBookInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.ID
     *
     * @return the value of tbl_book.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.ID
     *
     * @param ID the value for tbl_book.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.BookVenueID
     *
     * @return the value of tbl_book.BookVenueID
     *
     * @mbggenerated
     */
    public Integer getBookVenueID() {
        return bookVenueID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.BookVenueID
     *
     * @param bookVenueID the value for tbl_book.BookVenueID
     *
     * @mbggenerated
     */
    public void setBookVenueID(Integer bookVenueID) {
        this.bookVenueID = bookVenueID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.BookVenueSequence
     *
     * @return the value of tbl_book.BookVenueSequence
     *
     * @mbggenerated
     */
    public String getBookVenueSequence() {
        return bookVenueSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.BookVenueSequence
     *
     * @param bookVenueSequence the value for tbl_book.BookVenueSequence
     *
     * @mbggenerated
     */
    public void setBookVenueSequence(String bookVenueSequence) {
        this.bookVenueSequence = bookVenueSequence == null ? null : bookVenueSequence.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.BookCreateTIme
     *
     * @return the value of tbl_book.BookCreateTIme
     *
     * @mbggenerated
     */
    public Date getBookCreateTIme() {
        return bookCreateTIme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.BookCreateTIme
     *
     * @param bookCreateTIme the value for tbl_book.BookCreateTIme
     *
     * @mbggenerated
     */
    public void setBookCreateTIme(Date bookCreateTIme) {
        this.bookCreateTIme = bookCreateTIme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.BookBackgroundImg
     *
     * @return the value of tbl_book.BookBackgroundImg
     *
     * @mbggenerated
     */
    public String getBookBackgroundImg() {
        return bookBackgroundImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.BookBackgroundImg
     *
     * @param bookBackgroundImg the value for tbl_book.BookBackgroundImg
     *
     * @mbggenerated
     */
    public void setBookBackgroundImg(String bookBackgroundImg) {
        this.bookBackgroundImg = bookBackgroundImg == null ? null : bookBackgroundImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.BookFacebookLink
     *
     * @return the value of tbl_book.BookFacebookLink
     *
     * @mbggenerated
     */
    public String getBookFacebookLink() {
        return bookFacebookLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.BookFacebookLink
     *
     * @param bookFacebookLink the value for tbl_book.BookFacebookLink
     *
     * @mbggenerated
     */
    public void setBookFacebookLink(String bookFacebookLink) {
        this.bookFacebookLink = bookFacebookLink == null ? null : bookFacebookLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.BookTwitterLink
     *
     * @return the value of tbl_book.BookTwitterLink
     *
     * @mbggenerated
     */
    public String getBookTwitterLink() {
        return bookTwitterLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.BookTwitterLink
     *
     * @param bookTwitterLink the value for tbl_book.BookTwitterLink
     *
     * @mbggenerated
     */
    public void setBookTwitterLink(String bookTwitterLink) {
        this.bookTwitterLink = bookTwitterLink == null ? null : bookTwitterLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.BookWeixinLink
     *
     * @return the value of tbl_book.BookWeixinLink
     *
     * @mbggenerated
     */
    public String getBookWeixinLink() {
        return bookWeixinLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.BookWeixinLink
     *
     * @param bookWeixinLink the value for tbl_book.BookWeixinLink
     *
     * @mbggenerated
     */
    public void setBookWeixinLink(String bookWeixinLink) {
        this.bookWeixinLink = bookWeixinLink == null ? null : bookWeixinLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.BookWeiboLink
     *
     * @return the value of tbl_book.BookWeiboLink
     *
     * @mbggenerated
     */
    public String getBookWeiboLink() {
        return bookWeiboLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.BookWeiboLink
     *
     * @param bookWeiboLink the value for tbl_book.BookWeiboLink
     *
     * @mbggenerated
     */
    public void setBookWeiboLink(String bookWeiboLink) {
        this.bookWeiboLink = bookWeiboLink == null ? null : bookWeiboLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_book.AllCurBookInfo
     *
     * @return the value of tbl_book.AllCurBookInfo
     *
     * @mbggenerated
     */
    public String getAllCurBookInfo() {
        return allCurBookInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_book.AllCurBookInfo
     *
     * @param allCurBookInfo the value for tbl_book.AllCurBookInfo
     *
     * @mbggenerated
     */
    public void setAllCurBookInfo(String allCurBookInfo) {
        this.allCurBookInfo = allCurBookInfo == null ? null : allCurBookInfo.trim();
    }
}