package com.venues.bms.po;

import java.beans.Transient;
import java.util.Date;

import org.apache.commons.io.FileUtils;

public class FiAttach {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_attach.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_attach.Name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_attach.UrlPath
     *
     * @mbggenerated
     */
    private String urlPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_attach.Ext
     *
     * @mbggenerated
     */
    private String ext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_attach.Size
     *
     * @mbggenerated
     */
    private Long size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_attach.CreateTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_attach.ID
     *
     * @return the value of tbl_attach.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_attach.ID
     *
     * @param ID the value for tbl_attach.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_attach.Name
     *
     * @return the value of tbl_attach.Name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_attach.Name
     *
     * @param name the value for tbl_attach.Name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_attach.UrlPath
     *
     * @return the value of tbl_attach.UrlPath
     *
     * @mbggenerated
     */
    public String getUrlPath() {
        return urlPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_attach.UrlPath
     *
     * @param urlPath the value for tbl_attach.UrlPath
     *
     * @mbggenerated
     */
    public void setUrlPath(String urlPath) {
        this.urlPath = urlPath == null ? null : urlPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_attach.Ext
     *
     * @return the value of tbl_attach.Ext
     *
     * @mbggenerated
     */
    public String getExt() {
        return ext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_attach.Ext
     *
     * @param ext the value for tbl_attach.Ext
     *
     * @mbggenerated
     */
    public void setExt(String ext) {
        this.ext = ext == null ? null : ext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_attach.Size
     *
     * @return the value of tbl_attach.Size
     *
     * @mbggenerated
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_attach.Size
     *
     * @param size the value for tbl_attach.Size
     *
     * @mbggenerated
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_attach.CreateTime
     *
     * @return the value of tbl_attach.CreateTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_attach.CreateTime
     *
     * @param createTime the value for tbl_attach.CreateTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    /**
     **
	 * 获取当前附件的直接下载链接，当附件直接存放在web可下载目录是有效
	 * @return
	 */
	public String getDownloadPath() {
		return this.getUrlPath() + "/" + this.getName();
	}
	
	public String getDisplaySize() {
		return FileUtils.byteCountToDisplaySize(this.size);
	}

}