package com.venues.bms.po;

import java.util.Date;

public class FiFile extends FiFileKey {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_file.FileNameLocal
	 * 文件原始名称
	 * @mbggenerated
	 */
	private String fileNameLocal;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_file.FileNameServer
	 * 文件服务器名称
	 * @mbggenerated
	 */
	private String fileNameServer;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_file.FileUploadTime
	 * 上传时间
	 * @mbggenerated
	 */
	private Date fileUploadTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_file.Size
	 * 大小
	 * @mbggenerated
	 */
	private Float size;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_file.Ext
	 * 文件后缀名
	 * @mbggenerated
	 */
	private String ext;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_file.DescribeInfo
	 * 描述
	 * @mbggenerated
	 */
	private String describeInfo;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_file.UserVenueTypeID
	 *
	 * @mbggenerated
	 */
	private String userVenueTypeID;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_file.IsPass
	 *
	 * @mbggenerated
	 */
	private Integer isPass;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_file.FileNameLocal
	 *
	 * @return the value of tbl_file.FileNameLocal
	 *
	 * @mbggenerated
	 */
	public String getFileNameLocal() {
		return fileNameLocal;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_file.FileNameLocal
	 *
	 * @param fileNameLocal the value for tbl_file.FileNameLocal
	 *
	 * @mbggenerated
	 */
	public void setFileNameLocal(String fileNameLocal) {
		this.fileNameLocal = fileNameLocal == null ? null : fileNameLocal.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_file.FileNameServer
	 *
	 * @return the value of tbl_file.FileNameServer
	 *
	 * @mbggenerated
	 */
	public String getFileNameServer() {
		return fileNameServer;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_file.FileNameServer
	 *
	 * @param fileNameServer the value for tbl_file.FileNameServer
	 *
	 * @mbggenerated
	 */
	public void setFileNameServer(String fileNameServer) {
		this.fileNameServer = fileNameServer == null ? null : fileNameServer.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_file.FileUploadTime
	 *
	 * @return the value of tbl_file.FileUploadTime
	 *
	 * @mbggenerated
	 */
	public Date getFileUploadTime() {
		return fileUploadTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_file.FileUploadTime
	 *
	 * @param fileUploadTime the value for tbl_file.FileUploadTime
	 *
	 * @mbggenerated
	 */
	public void setFileUploadTime(Date fileUploadTime) {
		this.fileUploadTime = fileUploadTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_file.Size
	 *
	 * @return the value of tbl_file.Size
	 *
	 * @mbggenerated
	 */
	public Float getSize() {
		return size;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_file.Size
	 *
	 * @param size the value for tbl_file.Size
	 *
	 * @mbggenerated
	 */
	public void setSize(Float size) {
		this.size = size;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_file.Ext
	 *
	 * @return the value of tbl_file.Ext
	 *
	 * @mbggenerated
	 */
	public String getExt() {
		return ext;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_file.Ext
	 *
	 * @param ext the value for tbl_file.Ext
	 *
	 * @mbggenerated
	 */
	public void setExt(String ext) {
		this.ext = ext == null ? null : ext.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_file.DescribeInfo
	 *
	 * @return the value of tbl_file.DescribeInfo
	 *
	 * @mbggenerated
	 */
	public String getDescribeInfo() {
		return describeInfo;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_file.DescribeInfo
	 *
	 * @param describeInfo the value for tbl_file.DescribeInfo
	 *
	 * @mbggenerated
	 */
	public void setDescribeInfo(String describeInfo) {
		this.describeInfo = describeInfo == null ? null : describeInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_file.UserVenueTypeID
	 *
	 * @return the value of tbl_file.UserVenueTypeID
	 *
	 * @mbggenerated
	 */
	public String getUserVenueTypeID() {
		return userVenueTypeID;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_file.UserVenueTypeID
	 *
	 * @param userVenueTypeID the value for tbl_file.UserVenueTypeID
	 *
	 * @mbggenerated
	 */
	public void setUserVenueTypeID(String userVenueTypeID) {
		this.userVenueTypeID = userVenueTypeID == null ? null : userVenueTypeID.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_file.IsPass
	 *
	 * @return the value of tbl_file.IsPass
	 *
	 * @mbggenerated
	 */
	public Integer getIsPass() {
		return isPass;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_file.IsPass
	 *
	 * @param isPass the value for tbl_file.IsPass
	 *
	 * @mbggenerated
	 */
	public void setIsPass(Integer isPass) {
		this.isPass = isPass;
	}
}