package com.venues.bms.po;

public class FiFileKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_file.FileUserID
     *
     * @mbggenerated
     */
    private Integer fileUserID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_file.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_file.FileUserID
     *
     * @return the value of tbl_file.FileUserID
     *
     * @mbggenerated
     */
    public Integer getFileUserID() {
        return fileUserID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_file.FileUserID
     *
     * @param fileUserID the value for tbl_file.FileUserID
     *
     * @mbggenerated
     */
    public void setFileUserID(Integer fileUserID) {
        this.fileUserID = fileUserID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_file.ID
     *
     * @return the value of tbl_file.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_file.ID
     *
     * @param ID the value for tbl_file.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }
}