package com.venues.bms.po;

import java.util.Date;

public class GuComment {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_comment.ID
	 *
	 * @mbggenerated
	 */
	private Integer ID;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_comment.VenueID
	 *
	 * @mbggenerated
	 */
	private Integer venueID;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_comment.GuestID
	 *
	 * @mbggenerated
	 */
	private Integer guestID;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_comment.Content
	 *
	 * @mbggenerated
	 */
	private String content;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_comment.CreateTime
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_comment.LanguageCode
	 *
	 * @mbggenerated
	 */
	private String languageCode;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_comment.CommState
	 *
	 * @mbggenerated
	 */
	private String commState;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_comment.ID
	 *
	 * @return the value of tbl_comment.ID
	 *
	 * @mbggenerated
	 */
	public Integer getID() {
		return ID;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_comment.ID
	 *
	 * @param ID the value for tbl_comment.ID
	 *
	 * @mbggenerated
	 */
	public void setID(Integer ID) {
		this.ID = ID;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_comment.VenueID
	 *
	 * @return the value of tbl_comment.VenueID
	 *
	 * @mbggenerated
	 */
	public Integer getVenueID() {
		return venueID;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_comment.VenueID
	 *
	 * @param venueID the value for tbl_comment.VenueID
	 *
	 * @mbggenerated
	 */
	public void setVenueID(Integer venueID) {
		this.venueID = venueID;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_comment.GuestID
	 *
	 * @return the value of tbl_comment.GuestID
	 *
	 * @mbggenerated
	 */
	public Integer getGuestID() {
		return guestID;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_comment.GuestID
	 *
	 * @param guestID the value for tbl_comment.GuestID
	 *
	 * @mbggenerated
	 */
	public void setGuestID(Integer guestID) {
		this.guestID = guestID;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_comment.Content
	 *
	 * @return the value of tbl_comment.Content
	 *
	 * @mbggenerated
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_comment.Content
	 *
	 * @param content the value for tbl_comment.Content
	 *
	 * @mbggenerated
	 */
	public void setContent(String content) {
		this.content = content == null ? null : content.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_comment.CreateTime
	 *
	 * @return the value of tbl_comment.CreateTime
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_comment.CreateTime
	 *
	 * @param createTime the value for tbl_comment.CreateTime
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_comment.LanguageCode
	 *
	 * @return the value of tbl_comment.LanguageCode
	 *
	 * @mbggenerated
	 */
	public String getLanguageCode() {
		return languageCode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_comment.LanguageCode
	 *
	 * @param languageCode the value for tbl_comment.LanguageCode
	 *
	 * @mbggenerated
	 */
	public void setLanguageCode(String languageCode) {
		this.languageCode = languageCode == null ? null : languageCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_comment.CommState
	 *
	 * @return the value of tbl_comment.CommState
	 *
	 * @mbggenerated
	 */
	public String getCommState() {
		return commState;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_comment.CommState
	 *
	 * @param commState the value for tbl_comment.CommState
	 *
	 * @mbggenerated
	 */
	public void setCommState(String commState) {
		this.commState = commState == null ? null : commState.trim();
	}

	private String guestName;

	public String getGuestName() {
		return guestName;
	}

	public void setGuestName(String guestName) {
		this.guestName = guestName;
	}

}