package com.venues.bms.po;

import java.util.Date;

public class GuGuest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_guest.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_guest.GuestName
     *
     * @mbggenerated
     */
    private String guestName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_guest.GuestPassword
     *
     * @mbggenerated
     */
    private String guestPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_guest.GuestIP
     *
     * @mbggenerated
     */
    private String guestIP;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_guest.GuestEmail
     *
     * @mbggenerated
     */
    private String guestEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_guest.GuestContact
     *
     * @mbggenerated
     */
    private String guestContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_guest.GuestRemark
     *
     * @mbggenerated
     */
    private String guestRemark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_guest.GuestCreateTime
     *
     * @mbggenerated
     */
    private Date guestCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_guest.Region
     *
     * @mbggenerated
     */
    private String region;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_guest.Sector
     *
     * @mbggenerated
     */
    private String sector;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_guest.ID
     *
     * @return the value of tbl_guest.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_guest.ID
     *
     * @param ID the value for tbl_guest.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_guest.GuestName
     *
     * @return the value of tbl_guest.GuestName
     *
     * @mbggenerated
     */
    public String getGuestName() {
        return guestName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_guest.GuestName
     *
     * @param guestName the value for tbl_guest.GuestName
     *
     * @mbggenerated
     */
    public void setGuestName(String guestName) {
        this.guestName = guestName == null ? null : guestName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_guest.GuestPassword
     *
     * @return the value of tbl_guest.GuestPassword
     *
     * @mbggenerated
     */
    public String getGuestPassword() {
        return guestPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_guest.GuestPassword
     *
     * @param guestPassword the value for tbl_guest.GuestPassword
     *
     * @mbggenerated
     */
    public void setGuestPassword(String guestPassword) {
        this.guestPassword = guestPassword == null ? null : guestPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_guest.GuestIP
     *
     * @return the value of tbl_guest.GuestIP
     *
     * @mbggenerated
     */
    public String getGuestIP() {
        return guestIP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_guest.GuestIP
     *
     * @param guestIP the value for tbl_guest.GuestIP
     *
     * @mbggenerated
     */
    public void setGuestIP(String guestIP) {
        this.guestIP = guestIP == null ? null : guestIP.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_guest.GuestEmail
     *
     * @return the value of tbl_guest.GuestEmail
     *
     * @mbggenerated
     */
    public String getGuestEmail() {
        return guestEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_guest.GuestEmail
     *
     * @param guestEmail the value for tbl_guest.GuestEmail
     *
     * @mbggenerated
     */
    public void setGuestEmail(String guestEmail) {
        this.guestEmail = guestEmail == null ? null : guestEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_guest.GuestContact
     *
     * @return the value of tbl_guest.GuestContact
     *
     * @mbggenerated
     */
    public String getGuestContact() {
        return guestContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_guest.GuestContact
     *
     * @param guestContact the value for tbl_guest.GuestContact
     *
     * @mbggenerated
     */
    public void setGuestContact(String guestContact) {
        this.guestContact = guestContact == null ? null : guestContact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_guest.GuestRemark
     *
     * @return the value of tbl_guest.GuestRemark
     *
     * @mbggenerated
     */
    public String getGuestRemark() {
        return guestRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_guest.GuestRemark
     *
     * @param guestRemark the value for tbl_guest.GuestRemark
     *
     * @mbggenerated
     */
    public void setGuestRemark(String guestRemark) {
        this.guestRemark = guestRemark == null ? null : guestRemark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_guest.GuestCreateTime
     *
     * @return the value of tbl_guest.GuestCreateTime
     *
     * @mbggenerated
     */
    public Date getGuestCreateTime() {
        return guestCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_guest.GuestCreateTime
     *
     * @param guestCreateTime the value for tbl_guest.GuestCreateTime
     *
     * @mbggenerated
     */
    public void setGuestCreateTime(Date guestCreateTime) {
        this.guestCreateTime = guestCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_guest.Region
     *
     * @return the value of tbl_guest.Region
     *
     * @mbggenerated
     */
    public String getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_guest.Region
     *
     * @param region the value for tbl_guest.Region
     *
     * @mbggenerated
     */
    public void setRegion(String region) {
        this.region = region == null ? null : region.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_guest.Sector
     *
     * @return the value of tbl_guest.Sector
     *
     * @mbggenerated
     */
    public String getSector() {
        return sector;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_guest.Sector
     *
     * @param sector the value for tbl_guest.Sector
     *
     * @mbggenerated
     */
    public void setSector(String sector) {
        this.sector = sector == null ? null : sector.trim();
    }
}