package com.venues.bms.po;

public class MoModuleAttribute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module_attribute.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module_attribute.ModuleID
     *
     * @mbggenerated
     */
    private Integer moduleID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module_attribute.MAKey
     *
     * @mbggenerated
     */
    private Integer MAKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module_attribute.MAValue
     *
     * @mbggenerated
     */
    private String MAValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module_attribute.ID
     *
     * @return the value of tbl_module_attribute.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module_attribute.ID
     *
     * @param ID the value for tbl_module_attribute.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module_attribute.ModuleID
     *
     * @return the value of tbl_module_attribute.ModuleID
     *
     * @mbggenerated
     */
    public Integer getModuleID() {
        return moduleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module_attribute.ModuleID
     *
     * @param moduleID the value for tbl_module_attribute.ModuleID
     *
     * @mbggenerated
     */
    public void setModuleID(Integer moduleID) {
        this.moduleID = moduleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module_attribute.MAKey
     *
     * @return the value of tbl_module_attribute.MAKey
     *
     * @mbggenerated
     */
    public Integer getMAKey() {
        return MAKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module_attribute.MAKey
     *
     * @param MAKey the value for tbl_module_attribute.MAKey
     *
     * @mbggenerated
     */
    public void setMAKey(Integer MAKey) {
        this.MAKey = MAKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module_attribute.MAValue
     *
     * @return the value of tbl_module_attribute.MAValue
     *
     * @mbggenerated
     */
    public String getMAValue() {
        return MAValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module_attribute.MAValue
     *
     * @param MAValue the value for tbl_module_attribute.MAValue
     *
     * @mbggenerated
     */
    public void setMAValue(String MAValue) {
        this.MAValue = MAValue == null ? null : MAValue.trim();
    }
}