package com.venues.bms.po;

import java.util.Date;

public class MoModule {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.TemplateID
     *
     * @mbggenerated
     */
    private Integer templateID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.ModuleType
     *
     * @mbggenerated
     */
    private Integer moduleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.ModuleX
     *
     * @mbggenerated
     */
    private Integer moduleX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.ModuleY
     *
     * @mbggenerated
     */
    private Integer moduleY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.ModuleWidth
     *
     * @mbggenerated
     */
    private Integer moduleWidth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.ModuleHeight
     *
     * @mbggenerated
     */
    private Integer moduleHeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.ModuleImage
     *
     * @mbggenerated
     */
    private String moduleImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.ModuleDescriptions
     *
     * @mbggenerated
     */
    private String moduleDescriptions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.ModuleCreatetime
     *
     * @mbggenerated
     */
    private Date moduleCreatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.ModuleDepth
     *
     * @mbggenerated
     */
    private Integer moduleDepth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.TextPrompt
     *
     * @mbggenerated
     */
    private String textPrompt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.ReferModuleID
     *
     * @mbggenerated
     */
    private Integer referModuleID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.ReferX
     *
     * @mbggenerated
     */
    private Integer referX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_module.ReferY
     *
     * @mbggenerated
     */
    private Integer referY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.ID
     *
     * @return the value of tbl_module.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.ID
     *
     * @param ID the value for tbl_module.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.TemplateID
     *
     * @return the value of tbl_module.TemplateID
     *
     * @mbggenerated
     */
    public Integer getTemplateID() {
        return templateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.TemplateID
     *
     * @param templateID the value for tbl_module.TemplateID
     *
     * @mbggenerated
     */
    public void setTemplateID(Integer templateID) {
        this.templateID = templateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.ModuleType
     *
     * @return the value of tbl_module.ModuleType
     *
     * @mbggenerated
     */
    public Integer getModuleType() {
        return moduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.ModuleType
     *
     * @param moduleType the value for tbl_module.ModuleType
     *
     * @mbggenerated
     */
    public void setModuleType(Integer moduleType) {
        this.moduleType = moduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.ModuleX
     *
     * @return the value of tbl_module.ModuleX
     *
     * @mbggenerated
     */
    public Integer getModuleX() {
        return moduleX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.ModuleX
     *
     * @param moduleX the value for tbl_module.ModuleX
     *
     * @mbggenerated
     */
    public void setModuleX(Integer moduleX) {
        this.moduleX = moduleX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.ModuleY
     *
     * @return the value of tbl_module.ModuleY
     *
     * @mbggenerated
     */
    public Integer getModuleY() {
        return moduleY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.ModuleY
     *
     * @param moduleY the value for tbl_module.ModuleY
     *
     * @mbggenerated
     */
    public void setModuleY(Integer moduleY) {
        this.moduleY = moduleY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.ModuleWidth
     *
     * @return the value of tbl_module.ModuleWidth
     *
     * @mbggenerated
     */
    public Integer getModuleWidth() {
        return moduleWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.ModuleWidth
     *
     * @param moduleWidth the value for tbl_module.ModuleWidth
     *
     * @mbggenerated
     */
    public void setModuleWidth(Integer moduleWidth) {
        this.moduleWidth = moduleWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.ModuleHeight
     *
     * @return the value of tbl_module.ModuleHeight
     *
     * @mbggenerated
     */
    public Integer getModuleHeight() {
        return moduleHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.ModuleHeight
     *
     * @param moduleHeight the value for tbl_module.ModuleHeight
     *
     * @mbggenerated
     */
    public void setModuleHeight(Integer moduleHeight) {
        this.moduleHeight = moduleHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.ModuleImage
     *
     * @return the value of tbl_module.ModuleImage
     *
     * @mbggenerated
     */
    public String getModuleImage() {
        return moduleImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.ModuleImage
     *
     * @param moduleImage the value for tbl_module.ModuleImage
     *
     * @mbggenerated
     */
    public void setModuleImage(String moduleImage) {
        this.moduleImage = moduleImage == null ? null : moduleImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.ModuleDescriptions
     *
     * @return the value of tbl_module.ModuleDescriptions
     *
     * @mbggenerated
     */
    public String getModuleDescriptions() {
        return moduleDescriptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.ModuleDescriptions
     *
     * @param moduleDescriptions the value for tbl_module.ModuleDescriptions
     *
     * @mbggenerated
     */
    public void setModuleDescriptions(String moduleDescriptions) {
        this.moduleDescriptions = moduleDescriptions == null ? null : moduleDescriptions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.ModuleCreatetime
     *
     * @return the value of tbl_module.ModuleCreatetime
     *
     * @mbggenerated
     */
    public Date getModuleCreatetime() {
        return moduleCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.ModuleCreatetime
     *
     * @param moduleCreatetime the value for tbl_module.ModuleCreatetime
     *
     * @mbggenerated
     */
    public void setModuleCreatetime(Date moduleCreatetime) {
        this.moduleCreatetime = moduleCreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.ModuleDepth
     *
     * @return the value of tbl_module.ModuleDepth
     *
     * @mbggenerated
     */
    public Integer getModuleDepth() {
        return moduleDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.ModuleDepth
     *
     * @param moduleDepth the value for tbl_module.ModuleDepth
     *
     * @mbggenerated
     */
    public void setModuleDepth(Integer moduleDepth) {
        this.moduleDepth = moduleDepth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.TextPrompt
     *
     * @return the value of tbl_module.TextPrompt
     *
     * @mbggenerated
     */
    public String getTextPrompt() {
        return textPrompt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.TextPrompt
     *
     * @param textPrompt the value for tbl_module.TextPrompt
     *
     * @mbggenerated
     */
    public void setTextPrompt(String textPrompt) {
        this.textPrompt = textPrompt == null ? null : textPrompt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.ReferModuleID
     *
     * @return the value of tbl_module.ReferModuleID
     *
     * @mbggenerated
     */
    public Integer getReferModuleID() {
        return referModuleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.ReferModuleID
     *
     * @param referModuleID the value for tbl_module.ReferModuleID
     *
     * @mbggenerated
     */
    public void setReferModuleID(Integer referModuleID) {
        this.referModuleID = referModuleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.ReferX
     *
     * @return the value of tbl_module.ReferX
     *
     * @mbggenerated
     */
    public Integer getReferX() {
        return referX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.ReferX
     *
     * @param referX the value for tbl_module.ReferX
     *
     * @mbggenerated
     */
    public void setReferX(Integer referX) {
        this.referX = referX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_module.ReferY
     *
     * @return the value of tbl_module.ReferY
     *
     * @mbggenerated
     */
    public Integer getReferY() {
        return referY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_module.ReferY
     *
     * @param referY the value for tbl_module.ReferY
     *
     * @mbggenerated
     */
    public void setReferY(Integer referY) {
        this.referY = referY;
    }
}