package com.venues.bms.po;

import java.util.Date;

public class NeNews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_news.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_news.UserID
     *
     * @mbggenerated
     */
    private Integer userID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_news.NewsPage
     *
     * @mbggenerated
     */
    private Integer newsPage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_news.NewsTitle
     *
     * @mbggenerated
     */
    private String newsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_news.NewsAuthor
     *
     * @mbggenerated
     */
    private String newsAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_news.NewsSequence
     *
     * @mbggenerated
     */
    private Integer newsSequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_news.NewsCreateTime
     *
     * @mbggenerated
     */
    private Date newsCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_news.SmallImage
     *
     * @mbggenerated
     */
    private String smallImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_news.ID
     *
     * @return the value of tbl_news.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_news.ID
     *
     * @param ID the value for tbl_news.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_news.UserID
     *
     * @return the value of tbl_news.UserID
     *
     * @mbggenerated
     */
    public Integer getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_news.UserID
     *
     * @param userID the value for tbl_news.UserID
     *
     * @mbggenerated
     */
    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_news.NewsPage
     *
     * @return the value of tbl_news.NewsPage
     *
     * @mbggenerated
     */
    public Integer getNewsPage() {
        return newsPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_news.NewsPage
     *
     * @param newsPage the value for tbl_news.NewsPage
     *
     * @mbggenerated
     */
    public void setNewsPage(Integer newsPage) {
        this.newsPage = newsPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_news.NewsTitle
     *
     * @return the value of tbl_news.NewsTitle
     *
     * @mbggenerated
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_news.NewsTitle
     *
     * @param newsTitle the value for tbl_news.NewsTitle
     *
     * @mbggenerated
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle == null ? null : newsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_news.NewsAuthor
     *
     * @return the value of tbl_news.NewsAuthor
     *
     * @mbggenerated
     */
    public String getNewsAuthor() {
        return newsAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_news.NewsAuthor
     *
     * @param newsAuthor the value for tbl_news.NewsAuthor
     *
     * @mbggenerated
     */
    public void setNewsAuthor(String newsAuthor) {
        this.newsAuthor = newsAuthor == null ? null : newsAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_news.NewsSequence
     *
     * @return the value of tbl_news.NewsSequence
     *
     * @mbggenerated
     */
    public Integer getNewsSequence() {
        return newsSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_news.NewsSequence
     *
     * @param newsSequence the value for tbl_news.NewsSequence
     *
     * @mbggenerated
     */
    public void setNewsSequence(Integer newsSequence) {
        this.newsSequence = newsSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_news.NewsCreateTime
     *
     * @return the value of tbl_news.NewsCreateTime
     *
     * @mbggenerated
     */
    public Date getNewsCreateTime() {
        return newsCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_news.NewsCreateTime
     *
     * @param newsCreateTime the value for tbl_news.NewsCreateTime
     *
     * @mbggenerated
     */
    public void setNewsCreateTime(Date newsCreateTime) {
        this.newsCreateTime = newsCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_news.SmallImage
     *
     * @return the value of tbl_news.SmallImage
     *
     * @mbggenerated
     */
    public String getSmallImage() {
        return smallImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_news.SmallImage
     *
     * @param smallImage the value for tbl_news.SmallImage
     *
     * @mbggenerated
     */
    public void setSmallImage(String smallImage) {
        this.smallImage = smallImage == null ? null : smallImage.trim();
    }
}