package com.venues.bms.po;

public class PgPageContent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page_content.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page_content.PageID
     *
     * @mbggenerated
     */
    private Integer pageID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page_content.TemplateID
     *
     * @mbggenerated
     */
    private Integer templateID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page_content.ModuleID
     *
     * @mbggenerated
     */
    private Integer moduleID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page_content.ContentValue
     *
     * @mbggenerated
     */
    private String contentValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page_content.ContentSequence
     *
     * @mbggenerated
     */
    private Integer contentSequence;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page_content.ID
     *
     * @return the value of tbl_page_content.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page_content.ID
     *
     * @param ID the value for tbl_page_content.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page_content.PageID
     *
     * @return the value of tbl_page_content.PageID
     *
     * @mbggenerated
     */
    public Integer getPageID() {
        return pageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page_content.PageID
     *
     * @param pageID the value for tbl_page_content.PageID
     *
     * @mbggenerated
     */
    public void setPageID(Integer pageID) {
        this.pageID = pageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page_content.TemplateID
     *
     * @return the value of tbl_page_content.TemplateID
     *
     * @mbggenerated
     */
    public Integer getTemplateID() {
        return templateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page_content.TemplateID
     *
     * @param templateID the value for tbl_page_content.TemplateID
     *
     * @mbggenerated
     */
    public void setTemplateID(Integer templateID) {
        this.templateID = templateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page_content.ModuleID
     *
     * @return the value of tbl_page_content.ModuleID
     *
     * @mbggenerated
     */
    public Integer getModuleID() {
        return moduleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page_content.ModuleID
     *
     * @param moduleID the value for tbl_page_content.ModuleID
     *
     * @mbggenerated
     */
    public void setModuleID(Integer moduleID) {
        this.moduleID = moduleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page_content.ContentValue
     *
     * @return the value of tbl_page_content.ContentValue
     *
     * @mbggenerated
     */
    public String getContentValue() {
        return contentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page_content.ContentValue
     *
     * @param contentValue the value for tbl_page_content.ContentValue
     *
     * @mbggenerated
     */
    public void setContentValue(String contentValue) {
        this.contentValue = contentValue == null ? null : contentValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page_content.ContentSequence
     *
     * @return the value of tbl_page_content.ContentSequence
     *
     * @mbggenerated
     */
    public Integer getContentSequence() {
        return contentSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page_content.ContentSequence
     *
     * @param contentSequence the value for tbl_page_content.ContentSequence
     *
     * @mbggenerated
     */
    public void setContentSequence(Integer contentSequence) {
        this.contentSequence = contentSequence;
    }
}