package com.venues.bms.po;

import java.util.Date;

public class PgPage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page.TemplateID
     *
     * @mbggenerated
     */
    private Integer templateID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page.VenueID
     *
     * @mbggenerated
     */
    private Integer venueID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page.PageName
     *
     * @mbggenerated
     */
    private String pageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page.PageCreateTime
     *
     * @mbggenerated
     */
    private Date pageCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page.PageModifyTime
     *
     * @mbggenerated
     */
    private Date pageModifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page.PageDescription
     *
     * @mbggenerated
     */
    private String pageDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page.PageState
     *
     * @mbggenerated
     */
    private Integer pageState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page.PagePublish
     *
     * @mbggenerated
     */
    private Integer pagePublish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page.PageTypeID
     *
     * @mbggenerated
     */
    private Integer pageTypeID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page.Sequence
     *
     * @mbggenerated
     */
    private Integer sequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page.LikeCount
     *
     * @mbggenerated
     */
    private Integer likeCount;
    

    public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page.TemplateID
     *
     * @return the value of tbl_page.TemplateID
     *
     * @mbggenerated
     */
    public Integer getTemplateID() {
        return templateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page.TemplateID
     *
     * @param templateID the value for tbl_page.TemplateID
     *
     * @mbggenerated
     */
    public void setTemplateID(Integer templateID) {
        this.templateID = templateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page.VenueID
     *
     * @return the value of tbl_page.VenueID
     *
     * @mbggenerated
     */
    public Integer getVenueID() {
        return venueID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page.VenueID
     *
     * @param venueID the value for tbl_page.VenueID
     *
     * @mbggenerated
     */
    public void setVenueID(Integer venueID) {
        this.venueID = venueID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page.PageName
     *
     * @return the value of tbl_page.PageName
     *
     * @mbggenerated
     */
    public String getPageName() {
        return pageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page.PageName
     *
     * @param pageName the value for tbl_page.PageName
     *
     * @mbggenerated
     */
    public void setPageName(String pageName) {
        this.pageName = pageName == null ? null : pageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page.PageCreateTime
     *
     * @return the value of tbl_page.PageCreateTime
     *
     * @mbggenerated
     */
    public Date getPageCreateTime() {
        return pageCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page.PageCreateTime
     *
     * @param pageCreateTime the value for tbl_page.PageCreateTime
     *
     * @mbggenerated
     */
    public void setPageCreateTime(Date pageCreateTime) {
        this.pageCreateTime = pageCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page.PageModifyTime
     *
     * @return the value of tbl_page.PageModifyTime
     *
     * @mbggenerated
     */
    public Date getPageModifyTime() {
        return pageModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page.PageModifyTime
     *
     * @param pageModifyTime the value for tbl_page.PageModifyTime
     *
     * @mbggenerated
     */
    public void setPageModifyTime(Date pageModifyTime) {
        this.pageModifyTime = pageModifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page.PageDescription
     *
     * @return the value of tbl_page.PageDescription
     *
     * @mbggenerated
     */
    public String getPageDescription() {
        return pageDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page.PageDescription
     *
     * @param pageDescription the value for tbl_page.PageDescription
     *
     * @mbggenerated
     */
    public void setPageDescription(String pageDescription) {
        this.pageDescription = pageDescription == null ? null : pageDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page.PageState
     *
     * @return the value of tbl_page.PageState
     *
     * @mbggenerated
     */
    public Integer getPageState() {
        return pageState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page.PageState
     *
     * @param pageState the value for tbl_page.PageState
     *
     * @mbggenerated
     */
    public void setPageState(Integer pageState) {
        this.pageState = pageState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page.PagePublish
     *
     * @return the value of tbl_page.PagePublish
     *
     * @mbggenerated
     */
    public Integer getPagePublish() {
        return pagePublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page.PagePublish
     *
     * @param pagePublish the value for tbl_page.PagePublish
     *
     * @mbggenerated
     */
    public void setPagePublish(Integer pagePublish) {
        this.pagePublish = pagePublish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page.PageTypeID
     *
     * @return the value of tbl_page.PageTypeID
     *
     * @mbggenerated
     */
    public Integer getPageTypeID() {
        return pageTypeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page.PageTypeID
     *
     * @param pageTypeID the value for tbl_page.PageTypeID
     *
     * @mbggenerated
     */
    public void setPageTypeID(Integer pageTypeID) {
        this.pageTypeID = pageTypeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page.Sequence
     *
     * @return the value of tbl_page.Sequence
     *
     * @mbggenerated
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page.Sequence
     *
     * @param sequence the value for tbl_page.Sequence
     *
     * @mbggenerated
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page.LikeCount
     *
     * @return the value of tbl_page.LikeCount
     *
     * @mbggenerated
     */
    public Integer getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page.LikeCount
     *
     * @param likeCount the value for tbl_page.LikeCount
     *
     * @mbggenerated
     */
    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }
}