package com.venues.bms.po;

public class PgPageModuleAttribute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page_module_attribute.ID
     *
     * @mbggenerated
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page_module_attribute.PageID
     *
     * @mbggenerated
     */
    private Integer pageID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page_module_attribute.TmplateID
     *
     * @mbggenerated
     */
    private Integer tmplateID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page_module_attribute.ModuleID
     *
     * @mbggenerated
     */
    private Integer moduleID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page_module_attribute.MAKey
     *
     * @mbggenerated
     */
    private Integer MAKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_page_module_attribute.MAValue
     *
     * @mbggenerated
     */
    private String MAValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page_module_attribute.ID
     *
     * @return the value of tbl_page_module_attribute.ID
     *
     * @mbggenerated
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page_module_attribute.ID
     *
     * @param ID the value for tbl_page_module_attribute.ID
     *
     * @mbggenerated
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page_module_attribute.PageID
     *
     * @return the value of tbl_page_module_attribute.PageID
     *
     * @mbggenerated
     */
    public Integer getPageID() {
        return pageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page_module_attribute.PageID
     *
     * @param pageID the value for tbl_page_module_attribute.PageID
     *
     * @mbggenerated
     */
    public void setPageID(Integer pageID) {
        this.pageID = pageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page_module_attribute.TmplateID
     *
     * @return the value of tbl_page_module_attribute.TmplateID
     *
     * @mbggenerated
     */
    public Integer getTmplateID() {
        return tmplateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page_module_attribute.TmplateID
     *
     * @param tmplateID the value for tbl_page_module_attribute.TmplateID
     *
     * @mbggenerated
     */
    public void setTmplateID(Integer tmplateID) {
        this.tmplateID = tmplateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page_module_attribute.ModuleID
     *
     * @return the value of tbl_page_module_attribute.ModuleID
     *
     * @mbggenerated
     */
    public Integer getModuleID() {
        return moduleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page_module_attribute.ModuleID
     *
     * @param moduleID the value for tbl_page_module_attribute.ModuleID
     *
     * @mbggenerated
     */
    public void setModuleID(Integer moduleID) {
        this.moduleID = moduleID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page_module_attribute.MAKey
     *
     * @return the value of tbl_page_module_attribute.MAKey
     *
     * @mbggenerated
     */
    public Integer getMAKey() {
        return MAKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page_module_attribute.MAKey
     *
     * @param MAKey the value for tbl_page_module_attribute.MAKey
     *
     * @mbggenerated
     */
    public void setMAKey(Integer MAKey) {
        this.MAKey = MAKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_page_module_attribute.MAValue
     *
     * @return the value of tbl_page_module_attribute.MAValue
     *
     * @mbggenerated
     */
    public String getMAValue() {
        return MAValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_page_module_attribute.MAValue
     *
     * @param MAValue the value for tbl_page_module_attribute.MAValue
     *
     * @mbggenerated
     */
    public void setMAValue(String MAValue) {
        this.MAValue = MAValue == null ? null : MAValue.trim();
    }
}