package com.venues.bms.po;

import java.util.Date;

public class SaSales {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sales.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sales.UserID
     *
     * @mbggenerated
     */
    private Integer userID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sales.SalesPageID
     *
     * @mbggenerated
     */
    private Integer salesPageID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sales.SalesTitle
     *
     * @mbggenerated
     */
    private String salesTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sales.SalesVenueName
     *
     * @mbggenerated
     */
    private String salesVenueName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sales.SalesSequence
     *
     * @mbggenerated
     */
    private Integer salesSequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sales.SalesCreateTime
     *
     * @mbggenerated
     */
    private Date salesCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sales.SalesPublishID
     *
     * @mbggenerated
     */
    private Integer salesPublishID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sales.ID
     *
     * @return the value of tbl_sales.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sales.ID
     *
     * @param ID the value for tbl_sales.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sales.UserID
     *
     * @return the value of tbl_sales.UserID
     *
     * @mbggenerated
     */
    public Integer getUserID() {
        return userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sales.UserID
     *
     * @param userID the value for tbl_sales.UserID
     *
     * @mbggenerated
     */
    public void setUserID(Integer userID) {
        this.userID = userID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sales.SalesPageID
     *
     * @return the value of tbl_sales.SalesPageID
     *
     * @mbggenerated
     */
    public Integer getSalesPageID() {
        return salesPageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sales.SalesPageID
     *
     * @param salesPageID the value for tbl_sales.SalesPageID
     *
     * @mbggenerated
     */
    public void setSalesPageID(Integer salesPageID) {
        this.salesPageID = salesPageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sales.SalesTitle
     *
     * @return the value of tbl_sales.SalesTitle
     *
     * @mbggenerated
     */
    public String getSalesTitle() {
        return salesTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sales.SalesTitle
     *
     * @param salesTitle the value for tbl_sales.SalesTitle
     *
     * @mbggenerated
     */
    public void setSalesTitle(String salesTitle) {
        this.salesTitle = salesTitle == null ? null : salesTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sales.SalesVenueName
     *
     * @return the value of tbl_sales.SalesVenueName
     *
     * @mbggenerated
     */
    public String getSalesVenueName() {
        return salesVenueName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sales.SalesVenueName
     *
     * @param salesVenueName the value for tbl_sales.SalesVenueName
     *
     * @mbggenerated
     */
    public void setSalesVenueName(String salesVenueName) {
        this.salesVenueName = salesVenueName == null ? null : salesVenueName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sales.SalesSequence
     *
     * @return the value of tbl_sales.SalesSequence
     *
     * @mbggenerated
     */
    public Integer getSalesSequence() {
        return salesSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sales.SalesSequence
     *
     * @param salesSequence the value for tbl_sales.SalesSequence
     *
     * @mbggenerated
     */
    public void setSalesSequence(Integer salesSequence) {
        this.salesSequence = salesSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sales.SalesCreateTime
     *
     * @return the value of tbl_sales.SalesCreateTime
     *
     * @mbggenerated
     */
    public Date getSalesCreateTime() {
        return salesCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sales.SalesCreateTime
     *
     * @param salesCreateTime the value for tbl_sales.SalesCreateTime
     *
     * @mbggenerated
     */
    public void setSalesCreateTime(Date salesCreateTime) {
        this.salesCreateTime = salesCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sales.SalesPublishID
     *
     * @return the value of tbl_sales.SalesPublishID
     *
     * @mbggenerated
     */
    public Integer getSalesPublishID() {
        return salesPublishID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sales.SalesPublishID
     *
     * @param salesPublishID the value for tbl_sales.SalesPublishID
     *
     * @mbggenerated
     */
    public void setSalesPublishID(Integer salesPublishID) {
        this.salesPublishID = salesPublishID;
    }
}