package com.venues.bms.po;

public class SysAuthority {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_authority.AT_Id
     *
     * @mbggenerated
     */
    private Integer atId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_authority.AT_UserId
     *
     * @mbggenerated
     */
    private Integer atUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_authority.AT_MenuId
     *
     * @mbggenerated
     */
    private Integer atMenuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_authority.AT_UserTypeId
     *
     * @mbggenerated
     */
    private Integer atUsertypeid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_authority.AT_Id
     *
     * @return the value of tbl_sys_authority.AT_Id
     *
     * @mbggenerated
     */
    public Integer getAtId() {
        return atId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_authority.AT_Id
     *
     * @param atId the value for tbl_sys_authority.AT_Id
     *
     * @mbggenerated
     */
    public void setAtId(Integer atId) {
        this.atId = atId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_authority.AT_UserId
     *
     * @return the value of tbl_sys_authority.AT_UserId
     *
     * @mbggenerated
     */
    public Integer getAtUserid() {
        return atUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_authority.AT_UserId
     *
     * @param atUserid the value for tbl_sys_authority.AT_UserId
     *
     * @mbggenerated
     */
    public void setAtUserid(Integer atUserid) {
        this.atUserid = atUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_authority.AT_MenuId
     *
     * @return the value of tbl_sys_authority.AT_MenuId
     *
     * @mbggenerated
     */
    public Integer getAtMenuid() {
        return atMenuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_authority.AT_MenuId
     *
     * @param atMenuid the value for tbl_sys_authority.AT_MenuId
     *
     * @mbggenerated
     */
    public void setAtMenuid(Integer atMenuid) {
        this.atMenuid = atMenuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_authority.AT_UserTypeId
     *
     * @return the value of tbl_sys_authority.AT_UserTypeId
     *
     * @mbggenerated
     */
    public Integer getAtUsertypeid() {
        return atUsertypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_authority.AT_UserTypeId
     *
     * @param atUsertypeid the value for tbl_sys_authority.AT_UserTypeId
     *
     * @mbggenerated
     */
    public void setAtUsertypeid(Integer atUsertypeid) {
        this.atUsertypeid = atUsertypeid;
    }
}