package com.venues.bms.po;

public class SysDict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_dictionary.DA_Id
     *
     * @mbggenerated
     */
    private Integer daId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_dictionary.DA_Name
     *
     * @mbggenerated
     */
    private String daName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_dictionary.DA_Code
     *
     * @mbggenerated
     */
    private String daCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_dictionary.DA_ParentId
     *
     * @mbggenerated
     */
    private Integer daParentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_sys_dictionary.DA_Describe
     *
     * @mbggenerated
     */
    private String daDescribe;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_dictionary.DA_Id
     *
     * @return the value of tbl_sys_dictionary.DA_Id
     *
     * @mbggenerated
     */
    public Integer getDaId() {
        return daId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_dictionary.DA_Id
     *
     * @param daId the value for tbl_sys_dictionary.DA_Id
     *
     * @mbggenerated
     */
    public void setDaId(Integer daId) {
        this.daId = daId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_dictionary.DA_Name
     *
     * @return the value of tbl_sys_dictionary.DA_Name
     *
     * @mbggenerated
     */
    public String getDaName() {
        return daName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_dictionary.DA_Name
     *
     * @param daName the value for tbl_sys_dictionary.DA_Name
     *
     * @mbggenerated
     */
    public void setDaName(String daName) {
        this.daName = daName == null ? null : daName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_dictionary.DA_Code
     *
     * @return the value of tbl_sys_dictionary.DA_Code
     *
     * @mbggenerated
     */
    public String getDaCode() {
        return daCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_dictionary.DA_Code
     *
     * @param daCode the value for tbl_sys_dictionary.DA_Code
     *
     * @mbggenerated
     */
    public void setDaCode(String daCode) {
        this.daCode = daCode == null ? null : daCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_dictionary.DA_ParentId
     *
     * @return the value of tbl_sys_dictionary.DA_ParentId
     *
     * @mbggenerated
     */
    public Integer getDaParentid() {
        return daParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_dictionary.DA_ParentId
     *
     * @param daParentid the value for tbl_sys_dictionary.DA_ParentId
     *
     * @mbggenerated
     */
    public void setDaParentid(Integer daParentid) {
        this.daParentid = daParentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_sys_dictionary.DA_Describe
     *
     * @return the value of tbl_sys_dictionary.DA_Describe
     *
     * @mbggenerated
     */
    public String getDaDescribe() {
        return daDescribe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_sys_dictionary.DA_Describe
     *
     * @param daDescribe the value for tbl_sys_dictionary.DA_Describe
     *
     * @mbggenerated
     */
    public void setDaDescribe(String daDescribe) {
        this.daDescribe = daDescribe == null ? null : daDescribe.trim();
    }
}