package com.venues.bms.po;

import java.util.Date;

public class SysLog {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_sys_log.Log_Id
	 *
	 * @mbggenerated
	 */
	private Integer logId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_sys_log.Log_TypeId
	 *
	 * @mbggenerated
	 */
	private String logType;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_sys_log.Log_UserId
	 *
	 * @mbggenerated
	 */
	private String logUsername;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_sys_log.Log_MenuId
	 *
	 * @mbggenerated
	 */
	private String logTitle;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_sys_log.Log_Info
	 *
	 * @mbggenerated
	 */
	private String logInfo;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_sys_log.Log_Timestamp
	 *
	 * @mbggenerated
	 */
	private Date logTimestamp;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_sys_log.Log_Id
	 *
	 * @return the value of tbl_sys_log.Log_Id
	 *
	 * @mbggenerated
	 */
	public Integer getLogId() {
		return logId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_sys_log.Log_Id
	 *
	 * @param logId the value for tbl_sys_log.Log_Id
	 *
	 * @mbggenerated
	 */
	public void setLogId(Integer logId) {
		this.logId = logId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_sys_log.Log_TypeId
	 *
	 * @return the value of tbl_sys_log.Log_TypeId
	 *
	 * @mbggenerated
	 */
	public String getLogType() {
		return logType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_sys_log.Log_TypeId
	 *
	 * @param logTypeid the value for tbl_sys_log.Log_TypeId
	 *
	 * @mbggenerated
	 */
	public void setLogType(String logType) {
		this.logType = logType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_sys_log.Log_Info
	 *
	 * @return the value of tbl_sys_log.Log_Info
	 *
	 * @mbggenerated
	 */
	public String getLogInfo() {
		return logInfo;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_sys_log.Log_Info
	 *
	 * @param logInfo the value for tbl_sys_log.Log_Info
	 *
	 * @mbggenerated
	 */
	public void setLogInfo(String logInfo) {
		this.logInfo = logInfo == null ? null : logInfo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_sys_log.Log_Timestamp
	 *
	 * @return the value of tbl_sys_log.Log_Timestamp
	 *
	 * @mbggenerated
	 */
	public Date getLogTimestamp() {
		return logTimestamp;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_sys_log.Log_Timestamp
	 *
	 * @param logTimestamp the value for tbl_sys_log.Log_Timestamp
	 *
	 * @mbggenerated
	 */
	public void setLogTimestamp(Date logTimestamp) {
		this.logTimestamp = logTimestamp;
	}

	public String getLogUsername() {
		return logUsername;
	}

	public void setLogUsername(String logUsername) {
		this.logUsername = logUsername;
	}

	public String getLogTitle() {
		return logTitle;
	}

	public void setLogTitle(String logTitle) {
		this.logTitle = logTitle;
	}

}