package com.venues.bms.po;

import java.io.Serializable;
import java.util.List;

public class SysMenu implements Serializable {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_sys_menu.Menu_Id
	 *
	 * @mbggenerated
	 */
	private Integer menuId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_sys_menu.Menu_Name
	 *
	 * @mbggenerated
	 */
	private String menuName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_sys_menu.Menu_ParentId
	 *
	 * @mbggenerated
	 */
	private Integer menuParentid;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_sys_menu.Menu_IsMenu
	 *
	 * @mbggenerated
	 */
	private Boolean menuIsmenu;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_sys_menu.Menu_Url
	 *
	 * @mbggenerated
	 */
	private String menuUrl;

	private String menuIcon;

	private List<SysMenu> children;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_sys_menu.Menu_Id
	 *
	 * @return the value of tbl_sys_menu.Menu_Id
	 *
	 * @mbggenerated
	 */
	public Integer getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_sys_menu.Menu_Id
	 *
	 * @param menuId the value for tbl_sys_menu.Menu_Id
	 *
	 * @mbggenerated
	 */
	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_sys_menu.Menu_Name
	 *
	 * @return the value of tbl_sys_menu.Menu_Name
	 *
	 * @mbggenerated
	 */
	public String getMenuName() {
		return menuName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_sys_menu.Menu_Name
	 *
	 * @param menuName the value for tbl_sys_menu.Menu_Name
	 *
	 * @mbggenerated
	 */
	public void setMenuName(String menuName) {
		this.menuName = menuName == null ? null : menuName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_sys_menu.Menu_ParentId
	 *
	 * @return the value of tbl_sys_menu.Menu_ParentId
	 *
	 * @mbggenerated
	 */
	public Integer getMenuParentid() {
		return menuParentid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_sys_menu.Menu_ParentId
	 *
	 * @param menuParentid the value for tbl_sys_menu.Menu_ParentId
	 *
	 * @mbggenerated
	 */
	public void setMenuParentid(Integer menuParentid) {
		this.menuParentid = menuParentid;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_sys_menu.Menu_IsMenu
	 *
	 * @return the value of tbl_sys_menu.Menu_IsMenu
	 *
	 * @mbggenerated
	 */
	public Boolean getMenuIsmenu() {
		return menuIsmenu;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_sys_menu.Menu_IsMenu
	 *
	 * @param menuIsmenu the value for tbl_sys_menu.Menu_IsMenu
	 *
	 * @mbggenerated
	 */
	public void setMenuIsmenu(Boolean menuIsmenu) {
		this.menuIsmenu = menuIsmenu;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_sys_menu.Menu_Url
	 *
	 * @return the value of tbl_sys_menu.Menu_Url
	 *
	 * @mbggenerated
	 */
	public String getMenuUrl() {
		return menuUrl;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_sys_menu.Menu_Url
	 *
	 * @param menuUrl the value for tbl_sys_menu.Menu_Url
	 *
	 * @mbggenerated
	 */
	public void setMenuUrl(String menuUrl) {
		this.menuUrl = menuUrl == null ? null : menuUrl.trim();
	}

	public String getMenuIcon() {
		return menuIcon;
	}

	public void setMenuIcon(String menuIcon) {
		this.menuIcon = menuIcon == null ? null : menuIcon.trim();
	}

	public List<SysMenu> getChildren() {
		return children;
	}

	public void setChildren(List<SysMenu> children) {
		this.children = children;
	}

}