package com.venues.bms.po;

import java.util.Date;

public class TmpTemplate {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_template.ID
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_template.TemplateName
	 *
	 * @mbggenerated
	 */
	private String templateName;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_template.TemplateType
	 *
	 * @mbggenerated
	 */
	private Integer templateType;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_template.TemplateWidth
	 *
	 * @mbggenerated
	 */
	private Integer templateWidth;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_template.TemplateHeight
	 *
	 * @mbggenerated
	 */
	private Integer templateHeight;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_template.TemplateColor
	 *
	 * @mbggenerated
	 */
	private Integer templateColor;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_template.TemplateImage
	 *
	 * @mbggenerated
	 */
	private String templateImage;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_template.TemplateDescription
	 *
	 * @mbggenerated
	 */
	private String templateDescription;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_template.TemplateCreateTime
	 *
	 * @mbggenerated
	 */
	private Date templateCreateTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_template.smallImage
	 *
	 * @mbggenerated
	 */
	private String smallImage;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_template.ID
	 *
	 * @return the value of tbl_template.ID
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_template.ID
	 *
	 * @param ID the value for tbl_template.ID
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_template.TemplateName
	 *
	 * @return the value of tbl_template.TemplateName
	 *
	 * @mbggenerated
	 */
	public String getTemplateName() {
		return templateName;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_template.TemplateName
	 *
	 * @param templateName the value for tbl_template.TemplateName
	 *
	 * @mbggenerated
	 */
	public void setTemplateName(String templateName) {
		this.templateName = templateName == null ? null : templateName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_template.TemplateType
	 *
	 * @return the value of tbl_template.TemplateType
	 *
	 * @mbggenerated
	 */
	public Integer getTemplateType() {
		return templateType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_template.TemplateType
	 *
	 * @param templateType the value for tbl_template.TemplateType
	 *
	 * @mbggenerated
	 */
	public void setTemplateType(Integer templateType) {
		this.templateType = templateType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_template.TemplateWidth
	 *
	 * @return the value of tbl_template.TemplateWidth
	 *
	 * @mbggenerated
	 */
	public Integer getTemplateWidth() {
		return templateWidth;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_template.TemplateWidth
	 *
	 * @param templateWidth the value for tbl_template.TemplateWidth
	 *
	 * @mbggenerated
	 */
	public void setTemplateWidth(Integer templateWidth) {
		this.templateWidth = templateWidth;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_template.TemplateHeight
	 *
	 * @return the value of tbl_template.TemplateHeight
	 *
	 * @mbggenerated
	 */
	public Integer getTemplateHeight() {
		return templateHeight;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_template.TemplateHeight
	 *
	 * @param templateHeight the value for tbl_template.TemplateHeight
	 *
	 * @mbggenerated
	 */
	public void setTemplateHeight(Integer templateHeight) {
		this.templateHeight = templateHeight;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_template.TemplateColor
	 *
	 * @return the value of tbl_template.TemplateColor
	 *
	 * @mbggenerated
	 */
	public Integer getTemplateColor() {
		return templateColor;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_template.TemplateColor
	 *
	 * @param templateColor the value for tbl_template.TemplateColor
	 *
	 * @mbggenerated
	 */
	public void setTemplateColor(Integer templateColor) {
		this.templateColor = templateColor;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_template.TemplateImage
	 *
	 * @return the value of tbl_template.TemplateImage
	 *
	 * @mbggenerated
	 */
	public String getTemplateImage() {
		return templateImage;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_template.TemplateImage
	 *
	 * @param templateImage the value for tbl_template.TemplateImage
	 *
	 * @mbggenerated
	 */
	public void setTemplateImage(String templateImage) {
		this.templateImage = templateImage == null ? null : templateImage.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_template.TemplateDescription
	 *
	 * @return the value of tbl_template.TemplateDescription
	 *
	 * @mbggenerated
	 */
	public String getTemplateDescription() {
		return templateDescription;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_template.TemplateDescription
	 *
	 * @param templateDescription the value for tbl_template.TemplateDescription
	 *
	 * @mbggenerated
	 */
	public void setTemplateDescription(String templateDescription) {
		this.templateDescription = templateDescription == null ? null : templateDescription.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_template.TemplateCreateTime
	 *
	 * @return the value of tbl_template.TemplateCreateTime
	 *
	 * @mbggenerated
	 */
	public Date getTemplateCreateTime() {
		return templateCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_template.TemplateCreateTime
	 *
	 * @param templateCreateTime the value for tbl_template.TemplateCreateTime
	 *
	 * @mbggenerated
	 */
	public void setTemplateCreateTime(Date templateCreateTime) {
		this.templateCreateTime = templateCreateTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_template.smallImage
	 *
	 * @return the value of tbl_template.smallImage
	 *
	 * @mbggenerated
	 */
	public String getSmallImage() {
		return smallImage;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_template.smallImage
	 *
	 * @param smallImage the value for tbl_template.smallImage
	 *
	 * @mbggenerated
	 */
	public void setSmallImage(String smallImage) {
		this.smallImage = smallImage == null ? null : smallImage.trim();
	}
}