package com.venues.bms.po;

public class TmTheme {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_theme.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_theme.ThemeName
     *
     * @mbggenerated
     */
    private String themeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_theme.ThemeImage
     *
     * @mbggenerated
     */
    private String themeImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_theme.Sequence
     *
     * @mbggenerated
     */
    private Integer sequence;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_theme.ID
     *
     * @return the value of tbl_theme.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_theme.ID
     *
     * @param ID the value for tbl_theme.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_theme.ThemeName
     *
     * @return the value of tbl_theme.ThemeName
     *
     * @mbggenerated
     */
    public String getThemeName() {
        return themeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_theme.ThemeName
     *
     * @param themeName the value for tbl_theme.ThemeName
     *
     * @mbggenerated
     */
    public void setThemeName(String themeName) {
        this.themeName = themeName == null ? null : themeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_theme.ThemeImage
     *
     * @return the value of tbl_theme.ThemeImage
     *
     * @mbggenerated
     */
    public String getThemeImage() {
        return themeImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_theme.ThemeImage
     *
     * @param themeImage the value for tbl_theme.ThemeImage
     *
     * @mbggenerated
     */
    public void setThemeImage(String themeImage) {
        this.themeImage = themeImage == null ? null : themeImage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_theme.Sequence
     *
     * @return the value of tbl_theme.Sequence
     *
     * @mbggenerated
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_theme.Sequence
     *
     * @param sequence the value for tbl_theme.Sequence
     *
     * @mbggenerated
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }
}