package com.venues.bms.po;

public class TmThemeSalespage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_theme_salespage.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_theme_salespage.ThemeID
     *
     * @mbggenerated
     */
    private Integer themeID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_theme_salespage.SalePageID
     *
     * @mbggenerated
     */
    private Integer salePageID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_theme_salespage.ID
     *
     * @return the value of tbl_theme_salespage.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_theme_salespage.ID
     *
     * @param ID the value for tbl_theme_salespage.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_theme_salespage.ThemeID
     *
     * @return the value of tbl_theme_salespage.ThemeID
     *
     * @mbggenerated
     */
    public Integer getThemeID() {
        return themeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_theme_salespage.ThemeID
     *
     * @param themeID the value for tbl_theme_salespage.ThemeID
     *
     * @mbggenerated
     */
    public void setThemeID(Integer themeID) {
        this.themeID = themeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_theme_salespage.SalePageID
     *
     * @return the value of tbl_theme_salespage.SalePageID
     *
     * @mbggenerated
     */
    public Integer getSalePageID() {
        return salePageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_theme_salespage.SalePageID
     *
     * @param salePageID the value for tbl_theme_salespage.SalePageID
     *
     * @mbggenerated
     */
    public void setSalePageID(Integer salePageID) {
        this.salePageID = salePageID;
    }
}