package com.venues.bms.po;

import java.util.Date;

public class TplTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tpl_template.Id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tpl_template.TemplateName
     *
     * @mbggenerated
     */
    private String templateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tpl_template.TemplateType
     *
     * @mbggenerated
     */
    private String templateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tpl_template.TemplateDescription
     *
     * @mbggenerated
     */
    private String templateDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tpl_template.TemplateCreateTime
     *
     * @mbggenerated
     */
    private Date templateCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tpl_template.TemplateUpdateTime
     *
     * @mbggenerated
     */
    private Date templateUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tpl_template.UserId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tpl_template.TemplateContent
     *
     * @mbggenerated
     */
    private String templateContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tpl_template.Id
     *
     * @return the value of tbl_tpl_template.Id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tpl_template.Id
     *
     * @param id the value for tbl_tpl_template.Id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tpl_template.TemplateName
     *
     * @return the value of tbl_tpl_template.TemplateName
     *
     * @mbggenerated
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tpl_template.TemplateName
     *
     * @param templateName the value for tbl_tpl_template.TemplateName
     *
     * @mbggenerated
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tpl_template.TemplateType
     *
     * @return the value of tbl_tpl_template.TemplateType
     *
     * @mbggenerated
     */
    public String getTemplateType() {
        return templateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tpl_template.TemplateType
     *
     * @param templateType the value for tbl_tpl_template.TemplateType
     *
     * @mbggenerated
     */
    public void setTemplateType(String templateType) {
        this.templateType = templateType == null ? null : templateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tpl_template.TemplateDescription
     *
     * @return the value of tbl_tpl_template.TemplateDescription
     *
     * @mbggenerated
     */
    public String getTemplateDescription() {
        return templateDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tpl_template.TemplateDescription
     *
     * @param templateDescription the value for tbl_tpl_template.TemplateDescription
     *
     * @mbggenerated
     */
    public void setTemplateDescription(String templateDescription) {
        this.templateDescription = templateDescription == null ? null : templateDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tpl_template.TemplateCreateTime
     *
     * @return the value of tbl_tpl_template.TemplateCreateTime
     *
     * @mbggenerated
     */
    public Date getTemplateCreateTime() {
        return templateCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tpl_template.TemplateCreateTime
     *
     * @param templateCreateTime the value for tbl_tpl_template.TemplateCreateTime
     *
     * @mbggenerated
     */
    public void setTemplateCreateTime(Date templateCreateTime) {
        this.templateCreateTime = templateCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tpl_template.TemplateUpdateTime
     *
     * @return the value of tbl_tpl_template.TemplateUpdateTime
     *
     * @mbggenerated
     */
    public Date getTemplateUpdateTime() {
        return templateUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tpl_template.TemplateUpdateTime
     *
     * @param templateUpdateTime the value for tbl_tpl_template.TemplateUpdateTime
     *
     * @mbggenerated
     */
    public void setTemplateUpdateTime(Date templateUpdateTime) {
        this.templateUpdateTime = templateUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tpl_template.UserId
     *
     * @return the value of tbl_tpl_template.UserId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tpl_template.UserId
     *
     * @param userId the value for tbl_tpl_template.UserId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tpl_template.TemplateContent
     *
     * @return the value of tbl_tpl_template.TemplateContent
     *
     * @mbggenerated
     */
    public String getTemplateContent() {
        return templateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tpl_template.TemplateContent
     *
     * @param templateContent the value for tbl_tpl_template.TemplateContent
     *
     * @mbggenerated
     */
    public void setTemplateContent(String templateContent) {
        this.templateContent = templateContent == null ? null : templateContent.trim();
    }
}