package com.venues.bms.po;

public class VeVenueMeetingroom {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_meetingroom.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_meetingroom.VenueID
     *
     * @mbggenerated
     */
    private Integer venueID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_meetingroom.MRSequence
     *
     * @mbggenerated
     */
    private Integer MRSequence;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_meetingroom.FunctionRoom
     *
     * @mbggenerated
     */
    private String functionRoom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_meetingroom.Dimensions
     *
     * @mbggenerated
     */
    private String dimensions;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_meetingroom.Size
     *
     * @mbggenerated
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_meetingroom.Height
     *
     * @mbggenerated
     */
    private String height;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_meetingroom.Reception
     *
     * @mbggenerated
     */
    private String reception;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_meetingroom.Banquet
     *
     * @mbggenerated
     */
    private String banquet;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_meetingroom.Theatre
     *
     * @mbggenerated
     */
    private String theatre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_meetingroom.Classroom
     *
     * @mbggenerated
     */
    private String classroom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_meetingroom.UShape
     *
     * @mbggenerated
     */
    private String UShape;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_meetingroom.Boardroom
     *
     * @mbggenerated
     */
    private String boardroom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_meetingroom.HollowSquare
     *
     * @mbggenerated
     */
    private String hollowSquare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_meetingroom.MeetingImage
     *
     * @mbggenerated
     */
    private String meetingImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_meetingroom.ID
     *
     * @return the value of tbl_venue_meetingroom.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_meetingroom.ID
     *
     * @param ID the value for tbl_venue_meetingroom.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_meetingroom.VenueID
     *
     * @return the value of tbl_venue_meetingroom.VenueID
     *
     * @mbggenerated
     */
    public Integer getVenueID() {
        return venueID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_meetingroom.VenueID
     *
     * @param venueID the value for tbl_venue_meetingroom.VenueID
     *
     * @mbggenerated
     */
    public void setVenueID(Integer venueID) {
        this.venueID = venueID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_meetingroom.MRSequence
     *
     * @return the value of tbl_venue_meetingroom.MRSequence
     *
     * @mbggenerated
     */
    public Integer getMRSequence() {
        return MRSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_meetingroom.MRSequence
     *
     * @param MRSequence the value for tbl_venue_meetingroom.MRSequence
     *
     * @mbggenerated
     */
    public void setMRSequence(Integer MRSequence) {
        this.MRSequence = MRSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_meetingroom.FunctionRoom
     *
     * @return the value of tbl_venue_meetingroom.FunctionRoom
     *
     * @mbggenerated
     */
    public String getFunctionRoom() {
        return functionRoom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_meetingroom.FunctionRoom
     *
     * @param functionRoom the value for tbl_venue_meetingroom.FunctionRoom
     *
     * @mbggenerated
     */
    public void setFunctionRoom(String functionRoom) {
        this.functionRoom = functionRoom == null ? null : functionRoom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_meetingroom.Dimensions
     *
     * @return the value of tbl_venue_meetingroom.Dimensions
     *
     * @mbggenerated
     */
    public String getDimensions() {
        return dimensions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_meetingroom.Dimensions
     *
     * @param dimensions the value for tbl_venue_meetingroom.Dimensions
     *
     * @mbggenerated
     */
    public void setDimensions(String dimensions) {
        this.dimensions = dimensions == null ? null : dimensions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_meetingroom.Size
     *
     * @return the value of tbl_venue_meetingroom.Size
     *
     * @mbggenerated
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_meetingroom.Size
     *
     * @param size the value for tbl_venue_meetingroom.Size
     *
     * @mbggenerated
     */
    public void setSize(String size) {
        this.size = size == null ? null : size.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_meetingroom.Height
     *
     * @return the value of tbl_venue_meetingroom.Height
     *
     * @mbggenerated
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_meetingroom.Height
     *
     * @param height the value for tbl_venue_meetingroom.Height
     *
     * @mbggenerated
     */
    public void setHeight(String height) {
        this.height = height == null ? null : height.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_meetingroom.Reception
     *
     * @return the value of tbl_venue_meetingroom.Reception
     *
     * @mbggenerated
     */
    public String getReception() {
        return reception;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_meetingroom.Reception
     *
     * @param reception the value for tbl_venue_meetingroom.Reception
     *
     * @mbggenerated
     */
    public void setReception(String reception) {
        this.reception = reception == null ? null : reception.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_meetingroom.Banquet
     *
     * @return the value of tbl_venue_meetingroom.Banquet
     *
     * @mbggenerated
     */
    public String getBanquet() {
        return banquet;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_meetingroom.Banquet
     *
     * @param banquet the value for tbl_venue_meetingroom.Banquet
     *
     * @mbggenerated
     */
    public void setBanquet(String banquet) {
        this.banquet = banquet == null ? null : banquet.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_meetingroom.Theatre
     *
     * @return the value of tbl_venue_meetingroom.Theatre
     *
     * @mbggenerated
     */
    public String getTheatre() {
        return theatre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_meetingroom.Theatre
     *
     * @param theatre the value for tbl_venue_meetingroom.Theatre
     *
     * @mbggenerated
     */
    public void setTheatre(String theatre) {
        this.theatre = theatre == null ? null : theatre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_meetingroom.Classroom
     *
     * @return the value of tbl_venue_meetingroom.Classroom
     *
     * @mbggenerated
     */
    public String getClassroom() {
        return classroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_meetingroom.Classroom
     *
     * @param classroom the value for tbl_venue_meetingroom.Classroom
     *
     * @mbggenerated
     */
    public void setClassroom(String classroom) {
        this.classroom = classroom == null ? null : classroom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_meetingroom.UShape
     *
     * @return the value of tbl_venue_meetingroom.UShape
     *
     * @mbggenerated
     */
    public String getUShape() {
        return UShape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_meetingroom.UShape
     *
     * @param UShape the value for tbl_venue_meetingroom.UShape
     *
     * @mbggenerated
     */
    public void setUShape(String UShape) {
        this.UShape = UShape == null ? null : UShape.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_meetingroom.Boardroom
     *
     * @return the value of tbl_venue_meetingroom.Boardroom
     *
     * @mbggenerated
     */
    public String getBoardroom() {
        return boardroom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_meetingroom.Boardroom
     *
     * @param boardroom the value for tbl_venue_meetingroom.Boardroom
     *
     * @mbggenerated
     */
    public void setBoardroom(String boardroom) {
        this.boardroom = boardroom == null ? null : boardroom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_meetingroom.HollowSquare
     *
     * @return the value of tbl_venue_meetingroom.HollowSquare
     *
     * @mbggenerated
     */
    public String getHollowSquare() {
        return hollowSquare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_meetingroom.HollowSquare
     *
     * @param hollowSquare the value for tbl_venue_meetingroom.HollowSquare
     *
     * @mbggenerated
     */
    public void setHollowSquare(String hollowSquare) {
        this.hollowSquare = hollowSquare == null ? null : hollowSquare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_meetingroom.MeetingImage
     *
     * @return the value of tbl_venue_meetingroom.MeetingImage
     *
     * @mbggenerated
     */
    public String getMeetingImage() {
        return meetingImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_meetingroom.MeetingImage
     *
     * @param meetingImage the value for tbl_venue_meetingroom.MeetingImage
     *
     * @mbggenerated
     */
    public void setMeetingImage(String meetingImage) {
        this.meetingImage = meetingImage == null ? null : meetingImage.trim();
    }
}