package com.venues.bms.po;

public class VeVenueAttr {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue_attr.Id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue_attr.VenueId
	 * 关联场所
	 * @mbggenerated
	 */
	private Integer venueId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue_attr.Language
	 * 语言，关联字典
	 * @mbggenerated
	 */
	private String language;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue_attr.VenueType
	 * 场所类型，关联字典
	 * @mbggenerated
	 */
	private String venueType;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue_attr.AttrId
	 *
	 * @mbggenerated
	 */
	private Integer attrId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue_attr.AttrCode
	 *
	 * @mbggenerated
	 */
	private String attrCode;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue_attr.AttrValue
	 *
	 * @mbggenerated
	 */
	private String attrValue;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue_attr.Id
	 *
	 * @return the value of tbl_venue_attr.Id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue_attr.Id
	 *
	 * @param id the value for tbl_venue_attr.Id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue_attr.VenueId
	 *
	 * @return the value of tbl_venue_attr.VenueId
	 *
	 * @mbggenerated
	 */
	public Integer getVenueId() {
		return venueId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue_attr.VenueId
	 *
	 * @param venueId the value for tbl_venue_attr.VenueId
	 *
	 * @mbggenerated
	 */
	public void setVenueId(Integer venueId) {
		this.venueId = venueId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue_attr.Language
	 *
	 * @return the value of tbl_venue_attr.Language
	 *
	 * @mbggenerated
	 */
	public String getLanguage() {
		return language;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue_attr.Language
	 *
	 * @param language the value for tbl_venue_attr.Language
	 *
	 * @mbggenerated
	 */
	public void setLanguage(String language) {
		this.language = language == null ? null : language.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue_attr.VenueType
	 *
	 * @return the value of tbl_venue_attr.VenueType
	 *
	 * @mbggenerated
	 */
	public String getVenueType() {
		return venueType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue_attr.VenueType
	 *
	 * @param venueType the value for tbl_venue_attr.VenueType
	 *
	 * @mbggenerated
	 */
	public void setVenueType(String venueType) {
		this.venueType = venueType == null ? null : venueType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue_attr.AttrId
	 *
	 * @return the value of tbl_venue_attr.AttrId
	 *
	 * @mbggenerated
	 */
	public Integer getAttrId() {
		return attrId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue_attr.AttrId
	 *
	 * @param attrId the value for tbl_venue_attr.AttrId
	 *
	 * @mbggenerated
	 */
	public void setAttrId(Integer attrId) {
		this.attrId = attrId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue_attr.AttrCode
	 *
	 * @return the value of tbl_venue_attr.AttrCode
	 *
	 * @mbggenerated
	 */
	public String getAttrCode() {
		return attrCode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue_attr.AttrCode
	 *
	 * @param attrCode the value for tbl_venue_attr.AttrCode
	 *
	 * @mbggenerated
	 */
	public void setAttrCode(String attrCode) {
		this.attrCode = attrCode == null ? null : attrCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue_attr.AttrValue
	 *
	 * @return the value of tbl_venue_attr.AttrValue
	 *
	 * @mbggenerated
	 */
	public String getAttrValue() {
		return attrValue;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue_attr.AttrValue
	 *
	 * @param attrValue the value for tbl_venue_attr.AttrValue
	 *
	 * @mbggenerated
	 */
	public void setAttrValue(String attrValue) {
		this.attrValue = attrValue == null ? null : attrValue.trim();
	}
}