package com.venues.bms.po;

public class VeVenuePages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_pages.ID
     *
     * @mbggenerated
     */
    private Long ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_pages.VenueID
     *
     * @mbggenerated
     */
    private Integer venueID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_pages.PageID
     *
     * @mbggenerated
     */
    private Integer pageID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_pages.PageTypeID
     *
     * @mbggenerated
     */
    private Integer pageTypeID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_pages.ID
     *
     * @return the value of tbl_venue_pages.ID
     *
     * @mbggenerated
     */
    public Long getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_pages.ID
     *
     * @param ID the value for tbl_venue_pages.ID
     *
     * @mbggenerated
     */
    public void setID(Long ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_pages.VenueID
     *
     * @return the value of tbl_venue_pages.VenueID
     *
     * @mbggenerated
     */
    public Integer getVenueID() {
        return venueID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_pages.VenueID
     *
     * @param venueID the value for tbl_venue_pages.VenueID
     *
     * @mbggenerated
     */
    public void setVenueID(Integer venueID) {
        this.venueID = venueID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_pages.PageID
     *
     * @return the value of tbl_venue_pages.PageID
     *
     * @mbggenerated
     */
    public Integer getPageID() {
        return pageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_pages.PageID
     *
     * @param pageID the value for tbl_venue_pages.PageID
     *
     * @mbggenerated
     */
    public void setPageID(Integer pageID) {
        this.pageID = pageID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_pages.PageTypeID
     *
     * @return the value of tbl_venue_pages.PageTypeID
     *
     * @mbggenerated
     */
    public Integer getPageTypeID() {
        return pageTypeID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_pages.PageTypeID
     *
     * @param pageTypeID the value for tbl_venue_pages.PageTypeID
     *
     * @mbggenerated
     */
    public void setPageTypeID(Integer pageTypeID) {
        this.pageTypeID = pageTypeID;
    }
}