package com.venues.bms.po;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Map;

public class VeVenue {
	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue.ID
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue.VenueCode
	 *
	 * @mbggenerated
	 */
	private String venueCode;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue.VenueManager
	 *
	 * @mbggenerated
	 */
	private String venueManager;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue.VenueTypes
	 *
	 * @mbggenerated
	 */
	private String venueTypes;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue.Languages
	 *
	 * @mbggenerated
	 */
	private String languages;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue.StateId
	 *
	 * @mbggenerated
	 */
	private Integer stateId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue.ProvinceId
	 *
	 * @mbggenerated
	 */
	private Integer provinceId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue.CityId
	 *
	 * @mbggenerated
	 */
	private Integer cityId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue.Longitude
	 *
	 * @mbggenerated
	 */
	private BigDecimal longitude;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue.Latitude
	 *
	 * @mbggenerated
	 */
	private BigDecimal latitude;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue.Seq
	 *
	 * @mbggenerated
	 */
	private Integer seq;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue.ManagerId
	 *
	 * @mbggenerated
	 */
	private Integer managerId;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue.PayType
	 *
	 * @mbggenerated
	 */
	private String payType;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue.CreateTime
	 *
	 * @mbggenerated
	 */
	private Date createTime;

	/**
	 * This field was generated by MyBatis Generator.
	 * This field corresponds to the database column tbl_venue.CreateUserId
	 *
	 * @mbggenerated
	 */
	private Integer createUserId;

	private Map<String, VeVenueAttr> attrs;

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue.ID
	 *
	 * @return the value of tbl_venue.ID
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue.VenueCode
	 *
	 * @return the value of tbl_venue.VenueCode
	 *
	 * @mbggenerated
	 */
	public String getVenueCode() {
		return venueCode;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue.VenueCode
	 *
	 * @param venueCode the value for tbl_venue.VenueCode
	 *
	 * @mbggenerated
	 */
	public void setVenueCode(String venueCode) {
		this.venueCode = venueCode == null ? null : venueCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue.VenueManager
	 *
	 * @return the value of tbl_venue.VenueManager
	 *
	 * @mbggenerated
	 */
	public String getVenueManager() {
		return venueManager;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue.VenueManager
	 *
	 * @param venueManager the value for tbl_venue.VenueManager
	 *
	 * @mbggenerated
	 */
	public void setVenueManager(String venueManager) {
		this.venueManager = venueManager == null ? null : venueManager.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue.VenueTypes
	 *
	 * @return the value of tbl_venue.VenueTypes
	 *
	 * @mbggenerated
	 */
	public String getVenueTypes() {
		return venueTypes;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue.VenueTypes
	 *
	 * @param venueTypes the value for tbl_venue.VenueTypes
	 *
	 * @mbggenerated
	 */
	public void setVenueTypes(String venueTypes) {
		this.venueTypes = venueTypes == null ? null : venueTypes.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue.Languages
	 *
	 * @return the value of tbl_venue.Languages
	 *
	 * @mbggenerated
	 */
	public String getLanguages() {
		return languages;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue.Languages
	 *
	 * @param languages the value for tbl_venue.Languages
	 *
	 * @mbggenerated
	 */
	public void setLanguages(String languages) {
		this.languages = languages == null ? null : languages.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue.StateId
	 *
	 * @return the value of tbl_venue.StateId
	 *
	 * @mbggenerated
	 */
	public Integer getStateId() {
		return stateId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue.StateId
	 *
	 * @param stateId the value for tbl_venue.StateId
	 *
	 * @mbggenerated
	 */
	public void setStateId(Integer stateId) {
		this.stateId = stateId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue.ProvinceId
	 *
	 * @return the value of tbl_venue.ProvinceId
	 *
	 * @mbggenerated
	 */
	public Integer getProvinceId() {
		return provinceId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue.ProvinceId
	 *
	 * @param provinceId the value for tbl_venue.ProvinceId
	 *
	 * @mbggenerated
	 */
	public void setProvinceId(Integer provinceId) {
		this.provinceId = provinceId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue.CityId
	 *
	 * @return the value of tbl_venue.CityId
	 *
	 * @mbggenerated
	 */
	public Integer getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue.CityId
	 *
	 * @param cityId the value for tbl_venue.CityId
	 *
	 * @mbggenerated
	 */
	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue.Longitude
	 *
	 * @return the value of tbl_venue.Longitude
	 *
	 * @mbggenerated
	 */
	public BigDecimal getLongitude() {
		return longitude;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue.Longitude
	 *
	 * @param longitude the value for tbl_venue.Longitude
	 *
	 * @mbggenerated
	 */
	public void setLongitude(BigDecimal longitude) {
		this.longitude = longitude;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue.Latitude
	 *
	 * @return the value of tbl_venue.Latitude
	 *
	 * @mbggenerated
	 */
	public BigDecimal getLatitude() {
		return latitude;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue.Latitude
	 *
	 * @param latitude the value for tbl_venue.Latitude
	 *
	 * @mbggenerated
	 */
	public void setLatitude(BigDecimal latitude) {
		this.latitude = latitude;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue.Seq
	 *
	 * @return the value of tbl_venue.Seq
	 *
	 * @mbggenerated
	 */
	public Integer getSeq() {
		return seq;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue.Seq
	 *
	 * @param seq the value for tbl_venue.Seq
	 *
	 * @mbggenerated
	 */
	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue.ManagerId
	 *
	 * @return the value of tbl_venue.ManagerId
	 *
	 * @mbggenerated
	 */
	public Integer getManagerId() {
		return managerId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue.ManagerId
	 *
	 * @param managerId the value for tbl_venue.ManagerId
	 *
	 * @mbggenerated
	 */
	public void setManagerId(Integer managerId) {
		this.managerId = managerId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue.PayType
	 *
	 * @return the value of tbl_venue.PayType
	 *
	 * @mbggenerated
	 */
	public String getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue.PayType
	 *
	 * @param payType the value for tbl_venue.PayType
	 *
	 * @mbggenerated
	 */
	public void setPayType(String payType) {
		this.payType = payType == null ? null : payType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue.CreateTime
	 *
	 * @return the value of tbl_venue.CreateTime
	 *
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue.CreateTime
	 *
	 * @param createTime the value for tbl_venue.CreateTime
	 *
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method returns the value of the database column tbl_venue.CreateUserId
	 *
	 * @return the value of tbl_venue.CreateUserId
	 *
	 * @mbggenerated
	 */
	public Integer getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator.
	 * This method sets the value of the database column tbl_venue.CreateUserId
	 *
	 * @param createUserId the value for tbl_venue.CreateUserId
	 *
	 * @mbggenerated
	 */
	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	public Map<String, VeVenueAttr> getAttrs() {
		return attrs;
	}

	public void setAttrs(Map<String, VeVenueAttr> attrs) {
		this.attrs = attrs;
	}

}