package com.venues.bms.po;

public class VeVenueTemplate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_template.ID
     *
     * @mbggenerated
     */
    private Integer ID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_template.VenueID
     *
     * @mbggenerated
     */
    private Integer venueID;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_venue_template.TemplateID
     *
     * @mbggenerated
     */
    private Integer templateID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_template.ID
     *
     * @return the value of tbl_venue_template.ID
     *
     * @mbggenerated
     */
    public Integer getID() {
        return ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_template.ID
     *
     * @param ID the value for tbl_venue_template.ID
     *
     * @mbggenerated
     */
    public void setID(Integer ID) {
        this.ID = ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_template.VenueID
     *
     * @return the value of tbl_venue_template.VenueID
     *
     * @mbggenerated
     */
    public Integer getVenueID() {
        return venueID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_template.VenueID
     *
     * @param venueID the value for tbl_venue_template.VenueID
     *
     * @mbggenerated
     */
    public void setVenueID(Integer venueID) {
        this.venueID = venueID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_venue_template.TemplateID
     *
     * @return the value of tbl_venue_template.TemplateID
     *
     * @mbggenerated
     */
    public Integer getTemplateID() {
        return templateID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_venue_template.TemplateID
     *
     * @param templateID the value for tbl_venue_template.TemplateID
     *
     * @mbggenerated
     */
    public void setTemplateID(Integer templateID) {
        this.templateID = templateID;
    }
}