package com.venues.bms.dao;

import com.venues.bms.po.AdAdvert;

public interface AdAdvertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ad
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ad
     *
     * @mbggenerated
     */
    int insert(AdAdvert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ad
     *
     * @mbggenerated
     */
    int insertSelective(AdAdvert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ad
     *
     * @mbggenerated
     */
    AdAdvert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ad
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AdAdvert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_ad
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AdAdvert record);
}