package com.venues.bms.dao;

import com.venues.bms.po.AtAttrGroup;

public interface AtAttrGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_attr_group
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_attr_group
     *
     * @mbggenerated
     */
    int insert(AtAttrGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_attr_group
     *
     * @mbggenerated
     */
    int insertSelective(AtAttrGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_attr_group
     *
     * @mbggenerated
     */
    AtAttrGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_attr_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AtAttrGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_attr_group
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AtAttrGroup record);
}