package com.venues.bms.dao;

import com.venues.bms.po.AtAttr;

public interface AtAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_attr
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_attr
     *
     * @mbggenerated
     */
    int insert(AtAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_attr
     *
     * @mbggenerated
     */
    int insertSelective(AtAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_attr
     *
     * @mbggenerated
     */
    AtAttr selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_attr
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(AtAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_attr
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(AtAttr record);
}