package com.venues.bms.dao;

import com.venues.bms.po.BkBook;

public interface BkBookMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbggenerated
     */
    int insert(BkBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbggenerated
     */
    int insertSelective(BkBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbggenerated
     */
    BkBook selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BkBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(BkBook record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_book
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BkBook record);
}