package com.venues.bms.dao;

import com.venues.bms.po.FiAttach;

public interface FiAttachMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_attach
     *
     * @mbggenerated
     */
    int insert(FiAttach record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_attach
     *
     * @mbggenerated
     */
    int insertSelective(FiAttach record);
}