package com.venues.bms.dao;

import com.venues.bms.po.FiFile;
import com.venues.bms.po.FiFileKey;

public interface FiFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_file
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(FiFileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_file
     *
     * @mbggenerated
     */
    int insert(FiFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_file
     *
     * @mbggenerated
     */
    int insertSelective(FiFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_file
     *
     * @mbggenerated
     */
    FiFile selectByPrimaryKey(FiFileKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(FiFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(FiFile record);
}