package com.venues.bms.dao;

import java.util.List;
import java.util.Map;

import com.venues.bms.po.FiFile;

public interface FiFileMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_file
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer ID);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_file
	 *
	 * @mbggenerated
	 */
	int insert(FiFile record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_file
	 *
	 * @mbggenerated
	 */
	FiFile selectByPrimaryKey(Integer ID);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_file
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(FiFile record);

	int selectCountByParams(Map<String, Object> params);

	List<FiFile> selectByParams(Map<String, Object> params);
}