package com.venues.bms.dao;

import java.util.List;
import java.util.Map;

import com.venues.bms.po.GuComment;

public interface GuCommentMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_comment
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer ID);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_comment
	 *
	 * @mbggenerated
	 */
	int insert(GuComment record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_comment
	 *
	 * @mbggenerated
	 */
	int insertSelective(GuComment record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_comment
	 *
	 * @mbggenerated
	 */
	GuComment selectByPrimaryKey(Integer ID);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_comment
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(GuComment record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_comment
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(GuComment record);

	int selectCountByParams(Map<String, Object> params);

	List<GuComment> selectByParams(Map<String, Object> params);
}