package com.venues.bms.dao;

import com.venues.bms.po.GuGuestMessage;

public interface GuGuestMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_guest_message
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_guest_message
     *
     * @mbggenerated
     */
    int insert(GuGuestMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_guest_message
     *
     * @mbggenerated
     */
    int insertSelective(GuGuestMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_guest_message
     *
     * @mbggenerated
     */
    GuGuestMessage selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_guest_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GuGuestMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_guest_message
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GuGuestMessage record);
}