package com.venues.bms.dao;

import com.venues.bms.po.MoModuleAttribute;

public interface MoModuleAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_module_attribute
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_module_attribute
     *
     * @mbggenerated
     */
    int insert(MoModuleAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_module_attribute
     *
     * @mbggenerated
     */
    int insertSelective(MoModuleAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_module_attribute
     *
     * @mbggenerated
     */
    MoModuleAttribute selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_module_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(MoModuleAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_module_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(MoModuleAttribute record);
}