package com.venues.bms.dao;

import com.venues.bms.po.NeNews;

public interface NeNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_news
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_news
     *
     * @mbggenerated
     */
    int insert(NeNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_news
     *
     * @mbggenerated
     */
    int insertSelective(NeNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_news
     *
     * @mbggenerated
     */
    NeNews selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NeNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_news
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NeNews record);
}