package com.venues.bms.dao;

import java.util.List;
import java.util.Map;

import com.venues.bms.po.PgPageModuleAttribute;

public interface PgPageModuleAttributeMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_page_module_attribute
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Long ID);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_page_module_attribute
	 *
	 * @mbggenerated
	 */
	int insert(PgPageModuleAttribute record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_page_module_attribute
	 *
	 * @mbggenerated
	 */
	int insertSelective(PgPageModuleAttribute record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_page_module_attribute
	 *
	 * @mbggenerated
	 */
	PgPageModuleAttribute selectByPrimaryKey(Long ID);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_page_module_attribute
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PgPageModuleAttribute record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_page_module_attribute
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PgPageModuleAttribute record);

	List<PgPageModuleAttribute> selectByPageIdAndModuleId(Map<String, Object> param);
}