package com.venues.bms.dao;

import com.venues.bms.po.PgPageModuleAttribute;

public interface PgPageModuleAttributeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_page_module_attribute
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_page_module_attribute
     *
     * @mbggenerated
     */
    int insert(PgPageModuleAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_page_module_attribute
     *
     * @mbggenerated
     */
    int insertSelective(PgPageModuleAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_page_module_attribute
     *
     * @mbggenerated
     */
    PgPageModuleAttribute selectByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_page_module_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PgPageModuleAttribute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_page_module_attribute
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PgPageModuleAttribute record);
}