package com.venues.bms.dao;

import com.venues.bms.po.PgPageComment;

public interface PgPageCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_page_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_page_comment
     *
     * @mbggenerated
     */
    int insert(PgPageComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_page_comment
     *
     * @mbggenerated
     */
    int insertSelective(PgPageComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_page_comment
     *
     * @mbggenerated
     */
    PgPageComment selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_page_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PgPageComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_page_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PgPageComment record);
}