package com.venues.bms.dao;

import java.util.List;

import com.venues.bms.po.Region;

public interface RegionMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_region
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_region
	 *
	 * @mbggenerated
	 */
	int insert(Region record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_region
	 *
	 * @mbggenerated
	 */
	int insertSelective(Region record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_region
	 *
	 * @mbggenerated
	 */
	Region selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_region
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Region record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_region
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Region record);

	List<Region> selectByParentId(Integer parentId);
}