package com.venues.bms.dao;

import com.venues.bms.po.SaSales;

public interface SaSalesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sales
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sales
     *
     * @mbggenerated
     */
    int insert(SaSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sales
     *
     * @mbggenerated
     */
    int insertSelective(SaSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sales
     *
     * @mbggenerated
     */
    SaSales selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sales
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SaSales record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sales
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SaSales record);
}