package com.venues.bms.dao;

import com.venues.bms.po.SysDict;

public interface SysDictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_dictionary
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer daId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_dictionary
     *
     * @mbggenerated
     */
    int insert(SysDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_dictionary
     *
     * @mbggenerated
     */
    int insertSelective(SysDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_dictionary
     *
     * @mbggenerated
     */
    SysDict selectByPrimaryKey(Integer daId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysDict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_dictionary
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysDict record);
}