package com.venues.bms.dao;

import com.venues.bms.po.SysLog;

public interface SysLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_log
     *
     * @mbggenerated
     */
    int insert(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_log
     *
     * @mbggenerated
     */
    int insertSelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_log
     *
     * @mbggenerated
     */
    SysLog selectByPrimaryKey(Integer logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_sys_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysLog record);
}