package com.venues.bms.dao;

import java.util.List;
import java.util.Map;

import com.venues.bms.po.SysMenu;

public interface SysMenuMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_sys_menu
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer menuId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_sys_menu
	 *
	 * @mbggenerated
	 */
	int insert(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_sys_menu
	 *
	 * @mbggenerated
	 */
	int insertSelective(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_sys_menu
	 *
	 * @mbggenerated
	 */
	SysMenu selectByPrimaryKey(Integer menuId);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_sys_menu
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(SysMenu record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_sys_menu
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysMenu record);

	List<SysMenu> selectByParams(Map<String, Object> params);
}