package com.venues.bms.dao;

import java.util.List;
import java.util.Map;

import com.venues.bms.po.TmpTemplate;

public interface TmpTemplateMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_template
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_template
	 *
	 * @mbggenerated
	 */
	int insert(TmpTemplate record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_template
	 *
	 * @mbggenerated
	 */
	int insertSelective(TmpTemplate record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_template
	 *
	 * @mbggenerated
	 */
	TmpTemplate selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_template
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(TmpTemplate record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_template
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TmpTemplate record);

	int selectCountByParams(Map<String, Object> params);

	List<TmpTemplate> selectByParams(Map<String, Object> params);
}