package com.venues.bms.dao;

import com.venues.bms.po.TmpTemplate;

public interface TmpTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_template
     *
     * @mbggenerated
     */
    int insert(TmpTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_template
     *
     * @mbggenerated
     */
    int insertSelective(TmpTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_template
     *
     * @mbggenerated
     */
    TmpTemplate selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TmpTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TmpTemplate record);
}