package com.venues.bms.dao;

import com.venues.bms.po.TmThemeSalespage;

public interface TmThemeSalespageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_theme_salespage
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_theme_salespage
     *
     * @mbggenerated
     */
    int insert(TmThemeSalespage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_theme_salespage
     *
     * @mbggenerated
     */
    int insertSelective(TmThemeSalespage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_theme_salespage
     *
     * @mbggenerated
     */
    TmThemeSalespage selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_theme_salespage
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TmThemeSalespage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_theme_salespage
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TmThemeSalespage record);
}