package com.venues.bms.dao;

import java.util.List;
import java.util.Map;

import com.venues.bms.po.VeVenueAttr;

public interface VeVenueAttrMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_venue_attr
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_venue_attr
	 *
	 * @mbggenerated
	 */
	int insert(VeVenueAttr record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_venue_attr
	 *
	 * @mbggenerated
	 */
	int insertSelective(VeVenueAttr record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_venue_attr
	 *
	 * @mbggenerated
	 */
	VeVenueAttr selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_venue_attr
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(VeVenueAttr record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_venue_attr
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(VeVenueAttr record);

	List<VeVenueAttr> selectByVenueId(Integer venueId);

	List<VeVenueAttr> selectByCodeAndValue(Map<String, Object> params);
}