package com.venues.bms.dao;

import java.util.List;
import java.util.Map;

import com.venues.bms.po.VeVenueMeetingroom;

public interface VeVenueMeetingroomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_meetingroom
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_meetingroom
     *
     * @mbggenerated
     */
    int insert(VeVenueMeetingroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_meetingroom
     *
     * @mbggenerated
     */
    int insertSelective(VeVenueMeetingroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_meetingroom
     *
     * @mbggenerated
     */
    VeVenueMeetingroom selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_meetingroom
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VeVenueMeetingroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_meetingroom
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VeVenueMeetingroom record);

	List<VeVenueMeetingroom> selectByParams(Map<String, Object> params);
	
	int getMaxMRSequence(Integer venueID);
}