package com.venues.bms.dao;

import com.venues.bms.po.VeVenuePages;

public interface VeVenuePagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_pages
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_pages
     *
     * @mbggenerated
     */
    int insert(VeVenuePages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_pages
     *
     * @mbggenerated
     */
    int insertSelective(VeVenuePages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_pages
     *
     * @mbggenerated
     */
    VeVenuePages selectByPrimaryKey(Long ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_pages
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VeVenuePages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_pages
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VeVenuePages record);
}