package com.venues.bms.dao;

import java.util.List;
import java.util.Map;

import com.venues.bms.po.VeVenue;

public interface VeVenueMapper {
	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_venue
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_venue
	 *
	 * @mbggenerated
	 */
	int insert(VeVenue record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_venue
	 *
	 * @mbggenerated
	 */
	int insertSelective(VeVenue record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_venue
	 *
	 * @mbggenerated
	 */
	VeVenue selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_venue
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(VeVenue record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table tbl_venue
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(VeVenue record);

	int selectCountByParams(Map<String, Object> params);

	List<VeVenue> selectByParams(Map<String, Object> params);
}