package com.venues.bms.dao;

import com.venues.bms.po.VeVenueTemplate;

public interface VeVenueTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_template
     *
     * @mbggenerated
     */
    int insert(VeVenueTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_template
     *
     * @mbggenerated
     */
    int insertSelective(VeVenueTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_template
     *
     * @mbggenerated
     */
    VeVenueTemplate selectByPrimaryKey(Integer ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VeVenueTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_venue_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VeVenueTemplate record);
}